Add table oci_core_volume. Closes #6
turbot/steampipe-plugin-oci pull request #10
Opened 2021-03-24 14:51 UTC by khushboo9024

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
➜
SETUP: tests/oci_core_volume []

PRETEST: tests/oci_core_volume

TEST: tests/oci_core_volume
Running terraform
oci_core_volume.test_volume: Creating...
oci_core_volume.test_volume: Still creating... [10s elapsed]
oci_core_volume.test_volume: Creation complete after 15s [id=ocid1.volume.oc1.ap-mumbai-1.abrg6ljrawtdu5nvyjiwlbpqwn2cme23ggoq2f7gfsyztygd7ocr3j55jkra]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

freeform_tags = {
  "Name" = "turbottest65233"
}
resource_id = ocid1.volume.oc1.ap-mumbai-1.abrg6ljrawtdu5nvyjiwlbpqwn2cme23ggoq2f7gfsyztygd7ocr3j55jkra
tenancy_ocid = ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq

Running SQL query: test-get-query.sql
[
  {
    "id": "ocid1.volume.oc1.ap-mumbai-1.abrg6ljrawtdu5nvyjiwlbpqwn2cme23ggoq2f7gfsyztygd7ocr3j55jkra",
    "is_auto_tune_enabled": false,
    "is_hydrated": true,
    "lifecycle_state": "AVAILABLE",
    "size_in_gbs": 50
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "display_name": "abrg6ljrawtdu5nvyjiwlbpqwn2cme23ggoq2f7gfsyztygd7ocr3j55jkra",
    "id": "ocid1.volume.oc1.ap-mumbai-1.abrg6ljrawtdu5nvyjiwlbpqwn2cme23ggoq2f7gfsyztygd7ocr3j55jkra",
    "is_auto_tune_enabled": false,
    "is_hydrated": true,
    "lifecycle_state": "AVAILABLE",
    "size_in_gbs": 50
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "abrg6ljrawtdu5nvyjiwlbpqwn2cme23ggoq2f7gfsyztygd7ocr3j55jkra"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_volume

TEARDOWN: tests/oci_core_volume

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
```
### Basic info

select
  id,
  display_name,
  lifecycle_state,
  time_created
from
  oci_core_volume;

```
+-------------------------------------------------------------------------------------------+--------------+-----------------+-----------------------------------+
| id                                                                                        | display_name | lifecycle_state | time_created                      |
+-------------------------------------------------------------------------------------------+--------------+-----------------+-----------------------------------+
| ocid1.volume.oc1.ap-mumbai-1.abrg6ljrohtm2jp7aq2vtqioljzwjxevzuyl4hb5anfur4onruvthvbipk3a | Test12       | AVAILABLE       | 2021-03-23 08:34:20.831 +0000 UTC |
+-------------------------------------------------------------------------------------------+--------------+-----------------+-----------------------------------+
```
```

```
### List of volumes which are in faulty state
select
  id,
  display_name,
  lifecycle_state,
  time_created
from
  oci_core_volume
where
  lifecycle_state = 'FAULTY';
```
+----+--------------+-----------------+--------------+
| id | display_name | lifecycle_state | time_created |
+----+--------------+-----------------+--------------+
+----+--------------+-----------------+--------------+
```
```

### List of volumes with memory size greater than 1024 Gb
select
  id,
  display_name,
  lifecycle_state,
  size_in_gbs
from
  oci_core_volume
where
  size_in_gbs > 1024;

+-------------------------------------------------------------------------------------------+--------------+-----------------+-------------+
| id                                                                                        | display_name | lifecycle_state | size_in_gbs |
+-------------------------------------------------------------------------------------------+--------------+-----------------+-------------+
| ocid1.volume.oc1.ap-mumbai-1.abrg6ljrc5j5oobp763zqqgoce2iubl5f4hwkcjb6mfsfmivlpjlhsm67vca | TEST12       | AVAILABLE       | 1026        |
+-------------------------------------------------------------------------------------------+--------------+-----------------+-------------+

### Not found case for volume
> select
  id,
  display_name,
  lifecycle_state,
  time_created
from
 oci_core_volume where id = 'ocid1.volume.oc1.ap-mumbai-1.abrg6ljrsakhayihnmivogz62q5rthqk5fi4m3ni555va3mn4jiur3rfsdka::dummy'
+----+--------------+-----------------+--------------+
| id | display_name | lifecycle_state | time_created |
+----+--------------+-----------------+--------------+
+----+--------------+-----------------+--------------+
> 

> select
  id,
  display_name,
  lifecycle_state,
  time_created
from
  oci_new.oci_core_volume
where
  kms_key_id is null;
+-------------------------------------------------------------------------------------------+--------------+-----------------+---------------------+
| id                                                                                        | display_name | lifecycle_state | time_created        |
+-------------------------------------------------------------------------------------------+--------------+-----------------+---------------------+
| ocid1.volume.oc1.ap-mumbai-1.abrg6ljrtdijtusw5bv4w63o3fhcbk7trxytpdyaq2mywt2tdaac65g2xjcq | test         | AVAILABLE       | 2021-04-06 06:29:31 |
| ocid1.volume.oc1.iad.abuwcljrim5jusj43ugs3ccmv3gsgjlqbrdxrgmwxhfkpqqc7ehavgui4hla         | test-iad     | AVAILABLE       | 2021-04-06 06:36:12 |
+-------------------------------------------------------------------------------------------+--------------+-----------------+---------------------+

### List volumes with customer managed encryption

```sql
select
  id as volume_id,
  display_name,
  lifecycle_state,
  time_created
from
 oci_core_volume
where
  kms_key_id is not null;
  +-----------+--------------+-----------------+--------------+
| volume_id | display_name | lifecycle_state | time_created |
+-----------+--------------+-----------------+--------------+
+-----------+--------------+-----------------+--------------+
  
```
### List volumes created in the root compartment

```sql
select
  id as volume_id,
  display_name,
  lifecycle_state,
  tenant_id,
  compartment_id
from
  oci_core_volume
where
  compartment_id = tenant_id;

+-----------------------------------------------------------------------------------+--------------+-----------------+---------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| volume_id                                                                         | display_name | lifecycle_state | tenant_id                                                                       | compartment_id                                                                  |
+-----------------------------------------------------------------------------------+--------------+-----------------+---------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| ocid1.volume.oc1.iad.abuwcljrim5jusj43ugs3ccmv3gsgjlqbrdxrgmwxhfkpqqc7ehavgui4hla | test-iad     | AVAILABLE       | ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq | ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq |
+-----------------------------------------------------------------------------------+--------------+-----------------+---------------------------------------------------------------------------------+---------------------------------------------------------------------------------+

```

2021-04-06 08:52 UTC, rajmohanty17 commented on docs/tables/oci_core_volume.md
> +```
Is this correct ? we are saying ### List volumes with oracle managed encryption but the where condition is checking kms_key_id is null ?

2021-04-06 08:55 UTC, rajmohanty17 commented on docs/tables/oci_core_volume.md
> +  id,
select id > should we mention an alias for provide some info e.g. select id as volume_id.

2021-04-06 08:55 UTC, rajmohanty17 requested changes
Pls check the comments

2021-04-06 10:33 UTC, rajmohanty17 commented on docs/tables/oci_core_volume.md
> +```
@LalitTurbot this is bit confusing to let user know, that kms_key_id is null will indicate that, this is encrypted with oracle managed encryption. May be we can put a note

2021-04-08 08:20 UTC, rajmohanty17 requested changes
Can we identify the volumes are created in the root compartment ? This CIS requirement.

2021-04-08 10:25 UTC, rajmohanty17 approved these changes
LGTM

2021-04-08 13:38 UTC, cbruno10 approved these changes

2021-04-08 13:41 UTC, merged