Add table oci_identity_tag_namespace. Closes #104
turbot/steampipe-plugin-oci pull request #110
Opened 2021-05-04 12:37 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/azure_security_center []

PRETEST: tests/azure_security_center

TEST: tests/azure_security_center
Running terraform
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "az security auto-provisioning-setting list > /private/var/folders/d8/gsp6f_cn3359xnt_gs3cts_80000gn/T/tests/azure_security_center/terraform/test/autoProvision.json"]
null_resource.named_test_resource (local-exec): Command group 'security' is in preview. It may be changed/removed in a future release.
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "az security contact list > /private/var/folders/d8/gsp6f_cn3359xnt_gs3cts_80000gn/T/tests/azure_security_center/terraform/test/contact.json"]
null_resource.named_test_resource (local-exec): Command group 'security' is in preview. It may be changed/removed in a future release.
null_resource.named_test_resource: Creation complete after 8s [id=6875860449626536099]
data.local_file.input: Reading...
data.local_file.input_contact: Reading...
data.local_file.input_contact: Read complete after 0s [id=c72e80a56a92fbdd6fa46000e4b17ed6a0048f45]
data.local_file.input: Read complete after 0s [id=1a3745e7e4198e2ac2683f3d5eb79a75047e76c6]

Warning: Version constraints inside provider configuration blocks are deprecated

  on variables.tf line 22, in provider "azurerm":
  22:   version         = "=2.43.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

alert_notification = "Off"
alert_to_admin = "Off"
auto_provision = "Off"
contact_id = "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/Microsoft.Security/securityContacts/sourav-turbot.com"
email = "sourav@turbot.com"
name = "sourav-turbot.com"
provision_id = "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/Microsoft.Security/autoProvisioningSettings/default"

Running SQL query: test-list-query.sql
[
  {
    "auto_provisioning_settings": [
      {
        "id": "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/Microsoft.Security/autoProvisioningSettings/default",
        "name": "default",
        "properties": {
          "autoProvision": "Off"
        },
        "type": "Microsoft.Security/autoProvisioningSettings"
      }
    ],
    "contacts": [
      {
        "id": "/subscriptions/d7245080-b4ae-4fe5-b6fa-2e71b3dae6c8/providers/Microsoft.Security/securityContacts/sourav-turbot.com",
        "name": "sourav-turbot.com",
        "properties": {
          "alertNotifications": "Off",
          "alertsToAdmins": "Off",
          "email": "sourav@turbot.com",
          "phone": ""
        },
        "type": "Microsoft.Security/securityContacts"
      }
    ]
  }
]
✔ PASSED

POSTTEST: tests/azure_security_center

TEARDOWN: tests/azure_security_center

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
select
  name,
  id,
  is_retired,
  lifecycle_state
from
  oci_identity_tag_namespace;
+-------------+--------------------------------------------------------------------------------------+------------+-----------------+
| name        | id                                                                                   | is_retired | lifecycle_state |
+-------------+--------------------------------------------------------------------------------------+------------+-----------------+
| test        | ocid1.tagnamespace.oc1..aaaaaaaa4663ci3w42ujavuxoakkikxokgzrwmyfdstxin3exnmdldg6hnca | false      | ACTIVE          |
| Oracle-Tags | ocid1.tagnamespace.oc1..aaaaaaaal44hh2jnn3wbuvo7bb73poa4qpdvp6zzunynqh76fcn4jgld2h4q | false      | ACTIVE          |
+-------------+--------------------------------------------------------------------------------------+------------+-----------------+

 select
  name,
  id,
  is_retired,
  lifecycle_state
from
  oci_identity_tag_namespace
where
  lifecycle_state = 'ACTIVE';
+-------------+--------------------------------------------------------------------------------------+------------+-----------------+
| name        | id                                                                                   | is_retired | lifecycle_state |
+-------------+--------------------------------------------------------------------------------------+------------+-----------------+
| test        | ocid1.tagnamespace.oc1..aaaaaaaa4663ci3w42ujavuxoakkikxokgzrwmyfdstxin3exnmdldg6hnca | false      | ACTIVE          |
| Oracle-Tags | ocid1.tagnamespace.oc1..aaaaaaaal44hh2jnn3wbuvo7bb73poa4qpdvp6zzunynqh76fcn4jgld2h4q | false      | ACTIVE          |
+-------------+--------------------------------------------------------------------------------------+------------+-----------------+

select
  name,
  id,
  is_retired,
  lifecycle_state
from
  oci_identity_tag_namespace
where
  is_retired;
+------+--------------------------------------------------------------------------------------+------------+-----------------+
| name | id                                                                                   | is_retired | lifecycle_state |
+------+--------------------------------------------------------------------------------------+------------+-----------------+
| test | ocid1.tagnamespace.oc1..aaaaaaaa4663ci3w42ujavuxoakkikxokgzrwmyfdstxin3exnmdldg6hnca | true       | INACTIVE        |
+------+--------------------------------------------------------------------------------------+------------+-----------------+
```
</details>

2021-05-11 09:11 UTC, khushboo9024 commented on oci/table_oci_identity_tag_namespace.go
> +				Description: "Date and time the tagNamespace was created",
```suggestion
				Description: "Date and time the tagNamespace was created.",
```
`time_created` is important column, it should be above `description`.

2021-05-11 09:14 UTC, khushboo9024 requested changes
Integration test logs attached  is of `azure_security_center` , please update the logs.

2021-05-11 17:17 UTC, khushboo9024 approved these changes
LGTM

2021-05-17 07:29 UTC, rajmohanty17 approved these changes
LGTM

2021-05-19 21:06 UTC, cbruno10 approved these changes

2021-05-19 21:06 UTC, merged