Add table oci_core_boot_volume_backup. Closes #126
turbot/steampipe-plugin-oci pull request #129
Opened 2021-05-31 14:41 UTC by anisadas

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
### Basic info

```sql
select
  id,
  display_name,
  boot_volume_id,
  source_type,
  time_created,
  type,
  lifecycle_state as state
from
  oci_core_boot_volume_backup;
```
```
+-----------------------------------------------------------------------------------------------------+--------------+-------------------------------------------------------------------------
| id                                                                                                  | display_name | boot_volume_id                                                          
+-----------------------------------------------------------------------------------------------------+--------------+-------------------------------------------------------------------------
| ocid1.bootvolumebackup.oc1.ap-mumbai-1.abrg6ljr2a4kkd6lc5v62rvmtkrizycncoyokfre6zb57cjx7mejiw6xdmeq | testvolume   | ocid1.bootvolume.oc1.ap-mumbai-1.abrg6ljr6nf3gjka66a3mj5n3rze73tfw4ahx6f
| ocid1.bootvolumebackup.oc1.ap-mumbai-1.abrg6ljrsytlywkmhgp2ugt6kocapgiplds7kkshhjss2vslnlkqu2x6fsbq | volumebackup | ocid1.bootvolume.oc1.ap-mumbai-1.abrg6ljr6nf3gjka66a3mj5n3rze73tfw4ahx6f
+-----------------------------------------------------------------------------------------------------+--------------+-------------------------------------------------------------------------
```

### List manual boot volume backup

```sql
select
  id,
  display_name,
  source_type,
  time_created,
  type,
  lifecycle_state as state
from
  oci_core_boot_volume_backup
where
  source_type = 'MANUAL';
```
```
+-----------------------------------------------------------------------------------------------------+--------------+-------------+---------------------+---------------+--------------+
| id                                                                                                  | display_name | source_type | time_created        | type          | state        |
+-----------------------------------------------------------------------------------------------------+--------------+-------------+---------------------+---------------+--------------+
| ocid1.bootvolumebackup.oc1.ap-mumbai-1.abrg6ljr2a4kkd6lc5v62rvmtkrizycncoyokfre6zb57cjx7mejiw6xdmeq | testvolume   | MANUAL      | 2021-05-28 07:40:39 | "FULL"        | "TERMINATED" |
| ocid1.bootvolumebackup.oc1.ap-mumbai-1.abrg6ljrsytlywkmhgp2ugt6kocapgiplds7kkshhjss2vslnlkqu2x6fsbq | volumebackup | MANUAL      | 2021-05-31 06:38:34 | "INCREMENTAL" | "AVAILABLE"  |
+-----------------------------------------------------------------------------------------------------+--------------+-------------+---------------------+---------------+--------------+
```

2021-06-02 12:09 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Type:        proto.ColumnType_JSON,
```suggestion
				Type:        proto.ColumnType_STRING,
```
And this should be the 4th column.

2021-06-02 12:10 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Type:        proto.ColumnType_JSON,
```suggestion
				Type:        proto.ColumnType_STRING,
```

2021-06-02 12:25 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Transform:   transform.FromField("TimeCreated.Time"),
```suggestion
				Transform:   transform.FromField("TimeRequestReceived.Time"),
```

2021-06-02 12:26 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromCamel(),
```

2021-06-02 12:26 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromCamel(),
```

2021-06-02 12:26 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Type:        proto.ColumnType_STRING,
```suggestion
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromCamel(),
```

2021-06-02 12:28 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +	plugin.Logger(ctx).Trace("getImage")
```suggestion
	plugin.Logger(ctx).Trace("getBootVolumeBackup")
```

2021-06-02 12:28 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +	// handle empty image id in get call
```suggestion
	// handle empty boot volume backup id in get call
```

2021-06-02 12:29 UTC, khushboo9024 requested changes
Please check comments.

2021-06-02 13:49 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +			KeyColumns: plugin.AnyColumn([]string{"id"}),
```suggestion
				KeyColumns: plugin.SingleColumn("id"),
```

2021-06-02 14:45 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Description: "The OCID of the boot volume backup..",
```suggestion
				Description: "The OCID of the boot volume backup.",
```

2021-06-02 14:47 UTC, khushboo9024 commented on oci/table_oci_core_boot_volume_backup.go
> +				Transform:   transform.FromField("TimeCreated.Time"),
```suggestion
				Transform:   transform.FromField("ExpirationTime.Time"),
```

2021-06-03 08:05 UTC, anisadas commented
```
SETUP: tests/oci_core_boot_volume_backup []

PRETEST: tests/oci_core_boot_volume_backup

TEST: tests/oci_core_boot_volume_backup
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oci_core_boot_volume_backup.test_boot_volume_backup will be created
  + resource "oci_core_boot_volume_backup" "test_boot_volume_backup" {
      + boot_volume_id               = (known after apply)
      + compartment_id               = (known after apply)
      + defined_tags                 = (known after apply)
      + display_name                 = "steampipetest4815"
      + expiration_time              = (known after apply)
      + freeform_tags                = {
          + "Department" = "Finance"
        }
      + id                           = (known after apply)
      + image_id                     = (known after apply)
      + kms_key_id                   = (known after apply)
      + size_in_gbs                  = (known after apply)
      + source_boot_volume_backup_id = (known after apply)
      + source_type                  = (known after apply)
      + state                        = (known after apply)
      + system_tags                  = (known after apply)
      + time_created                 = (known after apply)
      + time_request_received        = (known after apply)
      + type                         = (known after apply)
      + unique_size_in_gbs           = (known after apply)
    }

  # oci_core_image.test_image will be created
  + resource "oci_core_image" "test_image" {
      + agent_features           = (known after apply)
      + base_image_id            = (known after apply)
      + billable_size_in_gbs     = (known after apply)
      + compartment_id           = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
      + create_image_allowed     = (known after apply)
      + defined_tags             = (known after apply)
      + display_name             = "steampipetest4815"
      + freeform_tags            = (known after apply)
      + id                       = (known after apply)
      + launch_mode              = (known after apply)
      + launch_options           = (known after apply)
      + listing_type             = (known after apply)
      + operating_system         = (known after apply)
      + operating_system_version = (known after apply)
      + size_in_mbs              = (known after apply)
      + state                    = (known after apply)
      + time_created             = (known after apply)

      + image_source_details {
          + bucket_name    = "steampipetest4815"
          + namespace_name = "bmqeqvslavsz"
          + object_name    = "test"
          + source_type    = "objectStorageTuple"
        }
    }

  # oci_core_instance.test_instance will be created
  + resource "oci_core_instance" "test_instance" {
      + availability_domain                 = "TvRS:AP-MUMBAI-1-AD-1"
      + boot_volume_id                      = (known after apply)
      + capacity_reservation_id             = (known after apply)
      + compartment_id                      = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
      + dedicated_vm_host_id                = (known after apply)
      + defined_tags                        = (known after apply)
      + display_name                        = (known after apply)
      + fault_domain                        = (known after apply)
      + freeform_tags                       = (known after apply)
      + hostname_label                      = (known after apply)
      + id                                  = (known after apply)
      + image                               = (known after apply)
      + ipxe_script                         = (known after apply)
      + is_pv_encryption_in_transit_enabled = (known after apply)
      + launch_mode                         = (known after apply)
      + preserve_boot_volume                = false
      + private_ip                          = (known after apply)
      + public_ip                           = (known after apply)
      + region                              = (known after apply)
      + shape                               = "VM.Standard.E2.1.Micro"
      + state                               = (known after apply)
      + subnet_id                           = (known after apply)
      + system_tags                         = (known after apply)
      + time_created                        = (known after apply)
      + time_maintenance_reboot_due         = (known after apply)

      + agent_config {
          + are_all_plugins_disabled = (known after apply)
          + is_management_disabled   = (known after apply)
          + is_monitoring_disabled   = (known after apply)

          + plugins_config {
              + desired_state = (known after apply)
              + name          = (known after apply)
            }
        }

      + availability_config {
          + is_live_migration_preferred = (known after apply)
          + recovery_action             = (known after apply)
        }

      + create_vnic_details {
          + assign_public_ip       = "true"
          + defined_tags           = (known after apply)
          + display_name           = (known after apply)
          + freeform_tags          = (known after apply)
          + hostname_label         = (known after apply)
          + private_ip             = (known after apply)
          + skip_source_dest_check = (known after apply)
          + subnet_id              = (known after apply)
          + vlan_id                = (known after apply)
        }

      + instance_options {
          + are_legacy_imds_endpoints_disabled = (known after apply)
        }

      + launch_options {
          + boot_volume_type                    = (known after apply)
          + firmware                            = (known after apply)
          + is_consistent_volume_naming_enabled = (known after apply)
          + is_pv_encryption_in_transit_enabled = (known after apply)
          + network_type                        = (known after apply)
          + remote_data_volume_type             = (known after apply)
        }

      + platform_config {
          + numa_nodes_per_socket = (known after apply)
          + type                  = (known after apply)
        }

      + preemptible_instance_config {
          + preemption_action {
              + preserve_boot_volume = (known after apply)
              + type                 = (known after apply)
            }
        }

      + shape_config {
          + baseline_ocpu_utilization     = (known after apply)
          + gpu_description               = (known after apply)
          + gpus                          = (known after apply)
          + local_disk_description        = (known after apply)
          + local_disks                   = (known after apply)
          + local_disks_total_size_in_gbs = (known after apply)
          + max_vnic_attachments          = (known after apply)
          + memory_in_gbs                 = (known after apply)
          + networking_bandwidth_in_gbps  = (known after apply)
          + ocpus                         = (known after apply)
          + processor_description         = (known after apply)
        }

      + source_details {
          + boot_volume_size_in_gbs = (known after apply)
          + kms_key_id              = (known after apply)
          + source_id               = (known after apply)
          + source_type             = "image"
        }
    }

  # oci_core_subnet.named_test_resource will be created
  + resource "oci_core_subnet" "named_test_resource" {
      + availability_domain        = (known after apply)
      + cidr_block                 = "10.0.0.0/16"
      + compartment_id             = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh [...]

2021-06-06 17:58 UTC, khushboo9024 approved these changes

2021-06-09 15:46 UTC, cbruno10 approved these changes

2021-06-09 15:46 UTC, merged