Add table oci_advanced_resource_query_search. Closes #108
turbot/steampipe-plugin-oci pull request #148
Opened 2021-06-23 10:29 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
SETUP: tests/oci_advanced_resource_query_search []

PRETEST: tests/oci_advanced_resource_query_search

TEST: tests/oci_advanced_resource_query_search
Running terraform
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "oci search resource structured-search --query-text 'query user resources' --output json > /private/var/folders/d8/gsp6f_cn3359xnt_gs3cts_80000gn/T/tests/oci_advanced_resource_query_search/terraform/test/output.json"]
null_resource.named_test_resource: Still creating... [10s elapsed]
null_resource.named_test_resource (local-exec): WARNING: Permissions on /Users/sourav/-04-08-07-40.pem are too open.
null_resource.named_test_resource (local-exec): To fix this please try executing the following command:
null_resource.named_test_resource (local-exec): oci setup repair-file-permissions --file /Users/sourav/-04-08-07-40.pem
null_resource.named_test_resource (local-exec): Alternatively to hide this warning, you may set the environment variable, OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING:
null_resource.named_test_resource (local-exec): export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True

null_resource.named_test_resource: Creation complete after 14s [id=4584857107387511354]
data.local_file.input: Reading...
data.local_file.input: Read complete after 0s [id=4dc9dbd52b05bdbc823201df3d4ac531b8909858]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

query = "query user resources"
resource_id = "ocid1.user.oc1..aaaaaaaaoze6lzv4vks2xpscxzvqiech3yuedts54o6v22kkud26khkaadsq"
resource_name = "oracleidentitycloudservice/raj@turbot.com"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"

Running SQL query: test-list-query.sql

[
  {
    "display_name": "oracleidentitycloudservice/raj@turbot.com",
    "identifier": "ocid1.user.oc1..aaaaaaaaoze6lzv4vks2xpscxzvqiech3yuedts54o6v22kkud26khkaadsq"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "oracleidentitycloudservice/raj@turbot.com"
  }
]
✔ PASSED

POSTTEST: tests/oci_advanced_resource_query_search

TEARDOWN: tests/oci_advanced_resource_query_search

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
select
  identifier,
  display_name,
  time_created,
  lifecycle_state as state
from
  oci_advanced_resource_query_search
where
  query = 'query volume, user resources'
+-------------------------------------------------------------------------------------------+--------------------------------------------------------------+---------------------+-----------+
| identifier                                                                                | display_name                                                 | time_created        | state     |
+-------------------------------------------------------------------------------------------+--------------------------------------------------------------+---------------------+-----------+
| ocid1.user.oc1..aaaaaaaa6bpjllytqwi5ktugtxs6edpcgapn6i6ka3jqjhwcwwxa7p5ynbaa              | lalit@turbot.com                                             | 2021-03-01 18:05:43 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaaoze6lzv4vks2xpscxzvqiech3yuedts54o6v22kkud26khkaadsq              | oracleidentitycloudservice/raj@turbot.com                    | 2021-06-17 11:19:21 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaa2a5gad6ili7376ncvckwpokxmnbuj4h2e7x4qsra2jkp76k4q4ka              | anisa                                                        | 2021-05-27 06:28:31 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaaao72k3wvyvcwdegwypfrvc4uinncv26d575li2f43jqkgb6hjfxq              | john                                                         | 2021-03-10 15:29:56 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaapp5zxoy3et5anwb7hq4yl47e64cj2xr4inpau3hzx6jghln7ufaa              | vishal                                                       | 2021-03-22 11:44:13 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaahqbqvodi7duwi5afwctrjd4phw6pje5fn232h7h2gp4n5tp6rska              | testDNS                                                      | 2021-05-28 09:10:58 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaan67wdtxru6otvrutqdsghruvgif4vyzkkfmzlsc2u5q35goj73ia              | rajesh_bal                                                   | 2021-03-22 11:42:46 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaaec2qfick343mgvatuzkd7z3onhmqanll7q5rvyuhnjtbznpqi7fq              | test                                                         | 2021-03-10 15:04:06 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaaqdsldjpzc6bnpym3btb4b2ztcc5khhl7rkoyjfaqkfxxltrhjbfq              | priyanka                                                     | 2021-05-27 06:26:10 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaackf6xvqlzl6bg2gawzp3hb3c7uzbulsms4c43kglzw62o7bayrka              | cody                                                         | 2021-03-22 11:28:10 | ACTIVE    |
| ocid1.volume.oc1.ap-mumbai-1.abrg6ljr2layofwlabpmo4widxmd73cdkbq7asi4ntjga45xcb6iv7lhkkza | abrg6ljr2layofwlabpmo4widxmd73cdkbq7asi4ntjga45xcb6iv7lhkkza | 2021-04-16 18:00:19 | AVAILABLE |
| ocid1.user.oc1..aaaaaaaa536mivetd3pnhdn24axarkutf7i75pky4f5yir2a762rttowno6q              | khushboo                                                     | 2021-03-22 11:23:38 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaa2wsgmjswz2fjzumysgukbdtoertf2pjggcgbm4xjn47yu5nhvqeq              | Turbot_Finance                                               | 2021-05-14 04:18:44 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaawbmubr6uathezmc34uqf2uoozujldhkgdbyozfhn6tij5ucfhvta              | oracleidentitycloudservice/lalit@turbot.com                  | 2021-03-01 19:08:30 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaafxtk2dxfkqaqr6df2oxg5ochplulp2ge2bwbf5wfksgg42fm4nlq              | puskar                                                       | 2021-05-27 06:06:59 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaarysamm5ofvbbqxs6gvslsdnqjex7rlrlndxiw2t6ln3aviply2yq              | subhajit                                                     | 2021-03-08 12:43:38 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaactz3m7balpusboxn2oixp7a3mpc6yife75v7a7o6c5d6wclrsjia              | lalit                                                        | 2021-03-01 18:07:54 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaazvio4hcyouxn2zd5latufffwyuwja7mwuj3zzpjqwz27x6pq4i2q              | sourav                                                       | 2021-04-08 06:45:13 | ACTIVE    |
| ocid1.volume.oc1.ap-mumbai-1.abrg6ljralp2cgeztd6c7j5oscgkm2tw3yov6ek6swjysulg7uv2hibgpv4q | abrg6ljralp2cgeztd6c7j5oscgkm2tw3yov6ek6swjysulg7uv2hibgpv4q | 2021-04-16 18:57:21 | AVAILABLE |
| ocid1.user.oc1..aaaaaaaar3qj7wzi2d2cwhq27q75ozllkjak522zwkw5phtnsshdpgmsh6la              | Raj                                                          | 2021-04-05 11:50:16 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaa2a5gad6ili7376ncvckwpokxmnbuj4h2e7x4qsra2jkp76k4q4ka              | anisa                                                        | 2021-05-27 06:28:31 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaar3qj7wzi2d2cwhq27q75ozllkjak522zwkw5phtnsshdpgmsh6la              | Raj                                                          | 2021-04-05 11:50:16 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaafxtk2dxfkqaqr6df2oxg5ochplulp2ge2bwbf5wfksgg42fm4nlq              | puskar                                                       | 2021-05-27 06:06:59 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaapp5zxoy3et5anwb7hq4yl47e64cj2xr4inpau3hzx6jghln7ufaa              | vishal                                                       | 2021-03-22 11:44:13 | ACTIVE    |
| ocid1.user.oc1..aaaaaaaaoze6lzv4vks2xpscxzvqiech3yuedts54o6v22kkud2 [...]

2021-06-29 09:54 UTC, rajmohanty17 commented on docs/tables/oci_advanced_resource_query_search.md
> +  query = 'query all resources';
@bigdatasourav let's cut this off to less output query.  We can make a specific call e.g 

```sql
select
  identifier,
  display_name,
  time_created,
  lifecycle_state as state
from
  oci_advanced_resource_query_search
where
  query = `query instance resources
    where lifeCycleState = 'RUNNING'`
```

2021-06-29 09:54 UTC, rajmohanty17 requested changes
Small change suggested

2021-06-29 10:53 UTC, rajmohanty17 approved these changes
LGTM

2021-06-30 16:27 UTC, cbruno10 requested changes
Please see comments

Also for table name, is this capability under a specific service, like `search` or `resource search`?

Looking at the Go SDK, there's another service, `LoggingSearch`, are there any other search type services we need to take into account?

Also, within the resource search API, are there other types of searches we can do? We can implement just this type for now, but should create a naming scheme that scales to other search types as well.

2021-06-30 16:27 UTC, cbruno10 commented on oci/service.go
> +	resourceSearchClient           resourcesearch.ResourceSearchClient
```suggestion
	ResourceSearchClient           resourcesearch.ResourceSearchClient
```

2021-06-30 16:27 UTC, cbruno10 commented on oci/table_oci_advanced_resource_query_search.go
> +				Name:        "search_region",
Is it common to change the standard `region` column name? If not, is there a reason we changed it here?

2021-07-01 14:18 UTC, cbruno10 commented on oci/table_oci_advanced_resource_query_search.go
> +				Name:        "search_region",
Confirmed with @bigdatasourav that this is by design per his conversation with @LalitTurbot

2021-07-01 20:18 UTC, cbruno10 commented
@bigdatasourav Does the free text API return the same data/type of data as the structured search? Depending on if we want 2 separate tables, or 1 combined, proposed table names are:

```
oci_resourcesearch_structured_query
oci_resourcesearch_free_text_query

or

oci_resource_search
```

2021-07-02 10:50 UTC, bigdatasourav commented
@cbruno10  response structure is same for both . Difference is only for the input  - input parameter -
1. resourcesearch.FreeTextSearchDetails which can take Text parameter.
2. resourcesearch.StructuredSearchDetails which can take Query parameter.

2021-07-08 15:10 UTC, bigdatasourav commented
```
> select identifier,display_name,time_created,lifecycle_state,query,text from oci_resource_search where query = 'query user resources'
+------------------------------------------------------------------------------+---------------------------------------------+---------------------+-----------------+----------------------+------+
| identifier                                                                   | display_name                                | time_created        | lifecycle_state | query                | text |
+------------------------------------------------------------------------------+---------------------------------------------+---------------------+-----------------+----------------------+------+
| ocid1.user.oc1..aaaaaaaa536mivetd3pnhdn24axarkutf7i75pky4f5yir2a762rttowno6q | khushboo                                    | 2021-03-22 11:23:38 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaawbmubr6uathezmc34uqf2uoozujldhkgdbyozfhn6tij5ucfhvta | oracleidentitycloudservice/lalit@turbot.com | 2021-03-01 19:08:30 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaqdsldjpzc6bnpym3btb4b2ztcc5khhl7rkoyjfaqkfxxltrhjbfq | priyanka                                    | 2021-05-27 06:26:10 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaactz3m7balpusboxn2oixp7a3mpc6yife75v7a7o6c5d6wclrsjia | lalit                                       | 2021-03-01 18:07:54 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaafxtk2dxfkqaqr6df2oxg5ochplulp2ge2bwbf5wfksgg42fm4nlq | puskar                                      | 2021-05-27 06:06:59 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaarysamm5ofvbbqxs6gvslsdnqjex7rlrlndxiw2t6ln3aviply2yq | subhajit                                    | 2021-03-08 12:43:38 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaahqbqvodi7duwi5afwctrjd4phw6pje5fn232h7h2gp4n5tp6rska | testDNS                                     | 2021-05-28 09:10:58 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaa2wsgmjswz2fjzumysgukbdtoertf2pjggcgbm4xjn47yu5nhvqeq | Turbot_Finance                              | 2021-05-14 04:18:44 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaa6bpjllytqwi5ktugtxs6edpcgapn6i6ka3jqjhwcwwxa7p5ynbaa | lalit@turbot.com                            | 2021-03-01 18:05:43 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaoze6lzv4vks2xpscxzvqiech3yuedts54o6v22kkud26khkaadsq | oracleidentitycloudservice/raj@turbot.com   | 2021-06-17 11:19:21 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaao72k3wvyvcwdegwypfrvc4uinncv26d575li2f43jqkgb6hjfxq | john                                        | 2021-03-10 15:29:56 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaackf6xvqlzl6bg2gawzp3hb3c7uzbulsms4c43kglzw62o7bayrka | cody                                        | 2021-03-22 11:28:10 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaar3qj7wzi2d2cwhq27q75ozllkjak522zwkw5phtnsshdpgmsh6la | Raj                                         | 2021-04-05 11:50:16 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaan67wdtxru6otvrutqdsghruvgif4vyzkkfmzlsc2u5q35goj73ia | rajesh_bal                                  | 2021-03-22 11:42:46 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaa2a5gad6ili7376ncvckwpokxmnbuj4h2e7x4qsra2jkp76k4q4ka | anisa                                       | 2021-05-27 06:28:31 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaapp5zxoy3et5anwb7hq4yl47e64cj2xr4inpau3hzx6jghln7ufaa | vishal                                      | 2021-03-22 11:44:13 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaeyky2derm4lqjosqlq27hg5lhomxolkkndxycbq7ln2e6txyeryq | oracleidentitycloudservice/krishna          | 2021-06-30 11:56:26 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaazvio4hcyouxn2zd5latufffwyuwja7mwuj3zzpjqwz27x6pq4i2q | sourav                                      | 2021-04-08 06:45:13 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaeyky2derm4lqjosqlq27hg5lhomxolkkndxycbq7ln2e6txyeryq | oracleidentitycloudservice/krishna          | 2021-06-30 11:56:26 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaqdsldjpzc6bnpym3btb4b2ztcc5khhl7rkoyjfaqkfxxltrhjbfq | priyanka                                    | 2021-05-27 06:26:10 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaafxtk2dxfkqaqr6df2oxg5ochplulp2ge2bwbf5wfksgg42fm4nlq | puskar                                      | 2021-05-27 06:06:59 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaoze6lzv4vks2xpscxzvqiech3yuedts54o6v22kkud26khkaadsq | oracleidentitycloudservice/raj@turbot.com   | 2021-06-17 11:19:21 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaahqbqvodi7duwi5afwctrjd4phw6pje5fn232h7h2gp4n5tp6rska | testDNS                                     | 2021-05-28 09:10:58 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaa536mivetd3pnhdn24axarkutf7i75pky4f5yir2a762rttowno6q | khushboo                                    | 2021-03-22 11:23:38 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaackf6xvqlzl6bg2gawzp3hb3c7uzbulsms4c43kglzw62o7bayrka | cody                                        | 2021-03-22 11:28:10 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaawbmubr6uathezmc34uqf2uoozujldhkgdbyozfhn6tij5ucfhvta | oracleidentitycloudservice/lalit@turbot.com | 2021-03-01 19:08:30 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaa2a5gad6ili7376ncvckwpokxmnbuj4h2e7x4qsra2jkp76k4q4ka | anisa                                       | 2021-05-27 06:28:31 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaactz3m7balpusboxn2oixp7a3mpc6yife75v7a7o6c5d6wclrsjia | lalit                                       | 2021-03-01 18:07:54 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaa2wsgmjswz2fjzumysgukbdtoertf2pjggcgbm4xjn47yu5nhvqeq | Turbot_Finance                              | 2021-05-14 04:18:44 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaa6bpjllytqwi5ktugtxs6edpcgapn6i6ka3jqjhwcwwxa7p5ynbaa | lalit@turbot.com                            | 2021-03-01 18:05:43 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaaao72k3wvyvcwdegwypfrvc4uinncv26d575li2f43jqkgb6hjfxq | john                                        | 2021-03-10 15:29:56 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaazvio4hcyouxn2zd5latufffwyuwja7mwuj3zzpjqwz27x6pq4i2q | sourav                                      | 2021-04-08 06:45:13 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaapp5zxoy3et5anwb7hq4yl47e64cj2xr4inpau3hzx6jghln7ufaa | vishal                                      | 2021-03-22 11:44:13 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaarysamm5ofvbbqxs6gvslsdnqjex7rlrlndxiw2t6ln3aviply2yq | subhajit                                    | 2021-03-08 12:43:38 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaan67wdtxru6otvrutqdsghruvgif4vyzkkfmzlsc2u5q35goj73ia | rajesh_bal                                  | 2021-03-22 11:42:46 | ACTIVE          | query user resources |      |
| ocid1.user.oc1..aaaaaaaar3qj7wzi2d2cwhq27q75ozllkjak522zwkw5phtnsshdpgmsh6la | Raj                                         | 2021-04-05 11:50:16 | ACTIVE          | query user resources |      |
+------------------------------------------------------------------------------+---------------------------------------------+---------------------+-----------------+------------ [...]

2021-08-16 08:34 UTC, rajlearner17 approved these changes
LGTM

2021-08-17 13:40 UTC, cbruno10 approved these changes

2021-08-17 13:44 UTC, merged