Add table oci_core_network_load_balancer. Closses #181
turbot/steampipe-plugin-oci pull request #224
Opened 2021-07-19 10:30 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Test names: [ 'tests/oci_core_network_load_balancer' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_core_network_load_balancer []

PRETEST: tests/oci_core_network_load_balancer

TEST: tests/oci_core_network_load_balancer
Running terraform
oci_core_vcn.named_test_resource: Creating...
oci_core_vcn.named_test_resource: Creation complete after 1s [id=ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaade665ppco24h4lb2hfq7j3h5ngale7zomk6dsbeyzs4q]
oci_core_subnet.named_test_resource: Creating...
oci_core_subnet.named_test_resource: Creation complete after 2s [id=ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaaluc2ihmirspss52h6m7amdwyupc42ceky23eq5y4jwz2d2zzjmhq]
oci_network_load_balancer_network_load_balancer.named_test_resource: Creating...
oci_network_load_balancer_network_load_balancer.named_test_resource: Still creating... [10s elapsed]
oci_network_load_balancer_network_load_balancer.named_test_resource: Still creating... [20s elapsed]
oci_network_load_balancer_network_load_balancer.named_test_resource: Creation complete after 24s [id=ocid1.networkloadbalancer.oc1.ap-mumbai-1.amaaaaaa6igdexaarxbvfywu7bfpakhnrxwe25sy5zmfb444xsn6roowgexq]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

display_name = "steampipetest2578"
freeform_tags = tomap({
  "Name" = "steampipetest2578"
})
is_preserve_source_destination = false
is_private = true
resource_id = "ocid1.networkloadbalancer.oc1.ap-mumbai-1.amaaaaaa6igdexaarxbvfywu7bfpakhnrxwe25sy5zmfb444xsn6roowgexq"
resource_name = "steampipetest2578"
state = "ACTIVE"
subnet_id = "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaaluc2ihmirspss52h6m7amdwyupc42ceky23eq5y4jwz2d2zzjmhq"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"

Running SQL query: test-get-query.sql

[
  {
    "display_name": "steampipetest2578",
    "freeform_tags": {
      "Name": "steampipetest2578"
    },
    "id": "ocid1.networkloadbalancer.oc1.ap-mumbai-1.amaaaaaa6igdexaarxbvfywu7bfpakhnrxwe25sy5zmfb444xsn6roowgexq",
    "is_private": true,
    "lifecycle_state": "ACTIVE",
    "subnet_id": "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaaluc2ihmirspss52h6m7amdwyupc42ceky23eq5y4jwz2d2zzjmhq"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "steampipetest2578",
    "id": "ocid1.networkloadbalancer.oc1.ap-mumbai-1.amaaaaaa6igdexaarxbvfywu7bfpakhnrxwe25sy5zmfb444xsn6roowgexq",
    "lifecycle_state": "ACTIVE",
    "subnet_id": "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaaluc2ihmirspss52h6m7amdwyupc42ceky23eq5y4jwz2d2zzjmhq"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "steampipetest2578"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_network_load_balancer

TEARDOWN: tests/oci_core_network_load_balancer

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  display_name,
  id,
  subnet_id,
  lifecycle_state as state,
  health_status,
  time_created
from
  oci_core_network_load_balancer;

+--------------------+--------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+--------+---------------+---------------------+
| display_name       | id                                                                                                     | subnet_id                                                                                 | state  | health_status | time_created        |
+--------------------+--------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+--------+---------------+---------------------+
| nlb_2021-0719-1022 | ocid1.networkloadbalancer.oc1.ap-mumbai-1.amaaaaaa6igdexaamgab5q5tvvgslnyzqwukcdcuwnomdi7aex47asazxtca | ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaar45zy3bfclbig7m6xrfrrlwwgaojokqgq5htc2ezog26i7p2ugtq | ACTIVE | OK            | 2021-07-19 04:53:37 |
+--------------------+--------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+--------+---------------+---------------------+
```

### List NLBs assigns with public IP address

```sql
select
  display_name,
  id,
  is_private
from
  oci_core_network_load_balancer
where
  not is_private;

+--------------------+--------------------------------------------------------------------------------------------------------+------------+
| display_name       | id                                                                                                     | is_private |
+--------------------+--------------------------------------------------------------------------------------------------------+------------+
| nlb_2021-0719-1022 | ocid1.networkloadbalancer.oc1.ap-mumbai-1.amaaaaaa6igdexaamgab5q5tvvgslnyzqwukcdcuwnomdi7aex47asazxtca | false      |
+--------------------+--------------------------------------------------------------------------------------------------------+------------+
```

### List unhealthy NLBs

```sql
select
  display_name,
  id,
  health_status
from
  oci_core_network_load_balancer
where
  health_status <> 'OK';

+--------------+----+---------------+
| display_name | id | health_status |
+--------------+----+---------------+
+--------------+----+---------------+
```
```
</details>

2021-07-19 10:39 UTC, bigdatasourav commented on docs/tables/oci_core_network_load_balancer.md
> +The Network Load Balancing (NLB) feature distributes traffic across several servers by using the TCP/IP networking protocol.
```suggestion
Network Load Balancers can provide automated traffic distribution from one entry point to multiple servers in a backend set. It ensure that your services remain available by directing traffic only to healthy servers. Network Load Balancer provides the benefits of flow high availability, source and destination IP addresses, and port preservation. It is designed to handle volatile traffic patterns and millions of flows, offering high throughput while maintaining ultra low latency. It is the ideal load balancing solution for latency sensitive workloads. It is also optimized for long-running connections in the order of days or months.
```

2021-07-19 10:40 UTC, bigdatasourav commented on docs/tables/oci_core_network_load_balancer.md
> +
```suggestion
```

2021-07-19 10:40 UTC, bigdatasourav commented on docs/tables/oci_core_network_load_balancer.md
> +
```suggestion
```

2021-07-19 10:44 UTC, bigdatasourav commented on docs/tables/oci_core_network_load_balancer.md
> +### List unhealthy NLBs
```suggestion
### List critical NLBs
```

2021-07-19 10:44 UTC, bigdatasourav commented on docs/tables/oci_core_network_load_balancer.md
> +  health_status <> 'OK';
```suggestion
  health_status = 'CRITICAL';
```

2021-07-19 10:45 UTC, bigdatasourav commented on oci-test/tests/oci_core_network_load_balancer/test-turbot-expected.json
> +    "region": "ap-mumbai-1",
Don't hard code region. use output variable.

2021-07-19 10:45 UTC, bigdatasourav commented on oci-test/tests/oci_core_network_load_balancer/variables.tf
> +  default     = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
```suggestion
  default     = ""
```

2021-07-19 11:13 UTC, bigdatasourav commented on oci/table_oci_core_network_load_balancer.go
> +				Name:        "health_status",
It should be a json column, also need to update the query.

2021-07-19 11:14 UTC, bigdatasourav commented on oci/table_oci_core_network_load_balancer.go
> +				Description: "The subnet in which the network load balancer is spawned OCIDs",
```suggestion
				Description: "The subnet in which the network load balancer is spawned OCIDs.",
```

2021-07-19 11:24 UTC, bigdatasourav commented on oci/table_oci_core_network_load_balancer.go
> +	if !strings.HasPrefix(compartment, "ocid1.tenancy.oc1") {
Will I get health details for NLBs which are not created in root?

2021-07-19 14:02 UTC, bigdatasourav requested changes
@rajeshbal65 plz check the requested changes

2021-07-20 10:32 UTC, bigdatasourav commented on oci/table_oci_core_network_load_balancer.go
> +				Name:        "network_load_balancer_health",
it should be after listeners, also sort the columns.

2021-07-20 11:27 UTC, bigdatasourav approved these changes
LGTM

2021-07-20 11:34 UTC, rajlearner17 approved these changes
LGTM

2021-07-21 06:43 UTC, merged