Add table oci_core_vcn. Closes #13
turbot/steampipe-plugin-oci pull request #23
Opened 2021-04-01 08:43 UTC by visiit

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
vishalkumar@Vishals-Air oci-test % ./tint.js tests/oci_core_vcn
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/oci_core_vcn []

PRETEST: tests/oci_core_vcn

TEST: tests/oci_core_vcn
Running terraform
oci_core_vcn.named_test_resource: Creating...
oci_core_vcn.named_test_resource: Creation complete after 5s [id=ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaao4teidp6wo6ywfdgiiotjaegngms75t6yzpfucw7i5eq]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

cidr_block = 10.0.0.0/16
resource_id = ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaao4teidp6wo6ywfdgiiotjaegngms75t6yzpfucw7i5eq
resource_name = turbottest74193
tenancy_ocid = ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq

Running SQL query: test-get-query.sql
[
  {
    "cidr_block": "10.0.0.0/16",
    "display_name": "turbottest74193",
    "id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaao4teidp6wo6ywfdgiiotjaegngms75t6yzpfucw7i5eq",
    "lifecycle_state": "AVAILABLE"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "cidr_block": "10.0.0.0/16",
    "display_name": "turbottest74193",
    "freeform_tags": {
      "Name": "turbottest74193"
    },
    "id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaao4teidp6wo6ywfdgiiotjaegngms75t6yzpfucw7i5eq",
    "lifecycle_state": "AVAILABLE"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "turbottest74193"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_vcn

TEARDOWN: tests/oci_core_vcn

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
- List all vcn

select
  display_name,
  id,
  lifecycle_state,
  cidr_block,
  freeform_tags
from
  oci_core_vcn;

+-----------------------+----------------------------------------------------------------------------------------+-----------------+-------------+----------------------+
| display_name          | id                                                                                     | lifecycle_state | cidr_block  | freeform_tags        |
+-----------------------+----------------------------------------------------------------------------------------+-----------------+-------------+----------------------+
| vcn-20210315-1512     | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaay3dsj7qq2vcugh66wiuru3odfpi6xnhdchgpugpbfx6q | AVAILABLE       | 10.0.0.0/16 | {}                   |
| vcn-20210308-2057     | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa5x3ugencwrt5mfbuxf5rvzknpwsdy63mt5tz2xnzpjma | AVAILABLE       | 10.0.0.0/16 | {}                   |
| turbot-test-steampipe | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa3serwetiodw7tm756kqkac7nyysutpi2itpmxw3cn4ua | AVAILABLE       | 10.0.0.0/16 | {"type":"steampipe"} |
| Test                  | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaab4nks5j6srt57zratcq7uee32e55mae3rcp6phkh6yia | AVAILABLE       | 10.0.0.0/24 | {}                   |
+-----------------------+----------------------------------------------------------------------------------------+-----------------+-------------+----------------------+

- Get a specific vcn

select
  display_name,
  id,
  lifecycle_state,
  cidr_block,
  dns_label
from
  oci_core_vcn
where
  id = 'ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaasn5aalvhjyqctaiykwy2bg3xjqeza6muotvya1wdrf4v';

+-----------------------+----------------------------------------------------------------------------------------+-----------------+-------------+------------+
| display_name          | id                                                                                     | lifecycle_state | cidr_block  | dns_label  |
+-----------------------+----------------------------------------------------------------------------------------+-----------------+-------------+------------+
| turbot-test-steampipe | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa3serwetiodw7tm756kqkac7nyysutpi2itpmxw3cn4ua | AVAILABLE       | 10.0.0.0/16 | turbottest |
+-----------------------+----------------------------------------------------------------------------------------+-----------------+-------------+------------+

- List of vcn where state is not available

select
  display_name,
  id,
  lifecycle_state
from
  oci_core_vcn
where
  lifecycle_state != 'AVAILABLE';

+--------------+----+-----------------+
| display_name | id | lifecycle_state |
+--------------+----+-----------------+
+--------------+----+-----------------+
```
</details>

2021-04-08 14:00 UTC, rajmohanty17 requested changes
Can I query this ?
2.5 Ensure the default security list of every VCN restricts all traffic except ICMP. I can explain yo

2021-04-08 14:25 UTC, visiit commented
@rajmohanty17  `oci_core_security_list` is another table in which we are capturing this.

2021-04-08 14:34 UTC, rajmohanty17 approved these changes
LGTM now

2021-04-14 19:17 UTC, cbruno10 approved these changes

2021-04-14 19:18 UTC, merged