Add table oci_mysql_configuration. CLoses #166
turbot/steampipe-plugin-oci pull request #255
Opened 2021-07-27 12:42 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Test names: [ 'tests/oci_mysql_configuration' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_mysql_configuration []

PRETEST: tests/oci_mysql_configuration

TEST: tests/oci_mysql_configuration
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.local_file.configuration will be read during apply
  # (config refers to values not yet known)
 <= data "local_file" "configuration"  {
      + content        = (known after apply)
      + content_base64 = (known after apply)
      + filename       = "/private/var/folders/vf/jz08tq5n02ncq2g4smq0v2dc0000gp/T/tests/oci_mysql_configuration/terraform/test/output.json"
      + id             = (known after apply)
    }

  # null_resource.named_test_resource will be created
  + resource "null_resource" "named_test_resource" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + lifecycle_state = (known after apply)
  + region          = "ap-mumbai-1"
  + resource_id     = (known after apply)
  + resource_name   = (known after apply)
  + shape_name      = (known after apply)
  + tenancy_ocid    = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
  + type            = (known after apply)
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "oci mysql configuration create --compartment-id ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq --shape-name VM.Standard.E2.1 --output json > /private/var/folders/vf/jz08tq5n02ncq2g4smq0v2dc0000gp/T/tests/oci_mysql_configuration/terraform/test/output.json"]
null_resource.named_test_resource: Creation complete after 4s [id=7496221466951651643]
data.local_file.configuration: Reading...
data.local_file.configuration: Read complete after 0s [id=b645e3b5de5dc3c1a718e41c6b55cd849e1d823c]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

lifecycle_state = "ACTIVE"
region = "ap-mumbai-1"
resource_id = "ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaka7pgbosxniagxkxbyuasofssnfwzbifjphho4tvzgfezsagd32a"
resource_name = "mysqlconfiguration20210727123149"
shape_name = "VM.Standard.E2.1"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
type = "CUSTOM"

Running SQL query: test-get-query.sql

[
  {
    "display_name": "mysqlconfiguration20210727123149",
    "id": "ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaka7pgbosxniagxkxbyuasofssnfwzbifjphho4tvzgfezsagd32a",
    "lifecycle_state": "ACTIVE",
    "shape_name": "VM.Standard.E2.1",
    "type": "CUSTOM"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "mysqlconfiguration20210727123149",
    "id": "ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaka7pgbosxniagxkxbyuasofssnfwzbifjphho4tvzgfezsagd32a",
    "lifecycle_state": "ACTIVE",
    "shape_name": "VM.Standard.E2.1",
    "type": "CUSTOM"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "mysqlconfiguration20210727123149"
  }
]
✔ PASSED

POSTTEST: tests/oci_mysql_configuration

TEARDOWN: tests/oci_mysql_configuration

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  display_name,
  id,
  description,
  lifecycle_state as state,
  time_created
from
  oci_mysql_configuration;

+-------------------------------------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+--------+---------------------+
| display_name                              | id                                                                                                    | description                                                                         | state  | time_created        |
+-------------------------------------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+--------+---------------------+
| VM.Standard.E2.8.Standalone               | ocid1.mysqlconfiguration.oc1..aaaaaaaah6o6qu3gdbxnqg6aw56amnosmnaycusttaa7abyq2tdgpgubvsgl            | Default Standalone configuration for the VM.Standard.E2.8 MySQL Shape               | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.VM.Standard.E3.64.1024GB.HA         | ocid1.mysqlconfiguration.oc1..aaaaaaaa2tiusjgxkqd344nbiv32rquejgzzo5mgwmvlpg2cay5ixl7sjv3a            | Default HA configuration for the MySQL.VM.Standard.E3.64.1024GB MySQL Shape         | ACTIVE | 2018-09-21 10:00:00 |
| VM.Standard.E2.1.Standalone               | ocid1.mysqlconfiguration.oc1..aaaaaaaah6o6qu3gdbxnqg6aw56amnosmnaycusttaa7abyq2tdgpgubvsgi            | Default Standalone configuration for the VM.Standard.E2.1 MySQL Shape               | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.VM.Standard.E3.1.8GB.HA             | ocid1.mysqlconfiguration.oc1..aaaaaaaantprksu6phqfgr5xvyut46wdfesdszonbclybfwvahgysfjbrb4q            | Default HA configuration for the MySQL.VM.Standard.E3.1.8GB MySQL Shape             | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.HeatWave.BM.Standard.E3.Standalone  | ocid1.mysqlconfiguration.oc1..aaaaaaaap7thcvkv3za4bbesmugyhtv7ogns7yvxiaw65c3c2efn22qb3iwa            | Default Standalone configuration for the MySQL.HeatWave.BM.Standard.E3 MySQL Shape  | ACTIVE | 2018-09-21 10:00:00 |
| BM.Standard.E2.64.Standalone              | ocid1.mysqlconfiguration.oc1..aaaaaaaah6o6qu3gdbxnqg6aw56amnosmnaycusttaa7abyq2tdgpgubvsgh            | Default Standalone configuration for the BM.Standard.E2.64 MySQL Shape              | ACTIVE | 2018-09-21 10:00:00 |
| VM.Standard.E2.2.Standalone               | ocid1.mysqlconfiguration.oc1..aaaaaaaah6o6qu3gdbxnqg6aw56amnosmnaycusttaa7abyq2tdgpgubvsgj            | Default Standalone configuration for the VM.Standard.E2.2 MySQL Shape               | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.VM.Standard.E3.1.16GB.HA            | ocid1.mysqlconfiguration.oc1..aaaaaaaahgiqob6oo3cwcoq2nbc3u2wz4uwlwblgyes6veogg6rv564aexwq            | Default HA configuration for the MySQL.VM.Standard.E3.1.16GB MySQL Shape            | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.VM.Standard.E3.1.8GB.Standalone     | ocid1.mysqlconfiguration.oc1..aaaaaaaalwzc2a22xqm56fwjwfymixnulmbq3v77p5v4lcbb6qhkftxf2trq            | Default Standalone configuration for the MySQL.VM.Standard.E3.1.8GB MySQL Shape     | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.VM.Standard.E3.16.256GB.Standalone  | ocid1.mysqlconfiguration.oc1..aaaaaaaafbsxowzfzxnnvm5mmmutrfl73hs2cv7ujgs7zqnzzw7v52fvihda            | Default Standalone configuration for the MySQL.VM.Standard.E3.16.256GB MySQL Shape  | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.VM.Standard.E3.2.32GB.HA            | ocid1.mysqlconfiguration.oc1..aaaaaaaah4ayiyeentcvebzlc5zw3u5otdlpupwkoyj566dukhp4ymz2yseq            | Default HA configuration for the MySQL.VM.Standard.E3.2.32GB MySQL Shape            | ACTIVE | 2018-09-21 10:00:00 |
| MySQL.VM.Standard.E3.1.16GB.Standalone    | ocid1.mysqlconfiguration.oc1..aaaaaaaaweky3hvms4bxw2uyf6pjcoxzf5gkqzxvxmzolgcu6bufd5bjnpyq            | Default Standalone configuration for the MySQL.VM.Standard.E3.1.16GB My [...]

2021-07-28 08:41 UTC, bigdatasourav commented on oci/service.go
> +func mySQLaasService(ctx context.Context, d *plugin.QueryData, region string) (*session, error) {
Fix the comment and cache key

2021-07-28 08:42 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +				Name:        "parent_configuration_id",
parent_configuration_id should be in top columns and description in other columns

2021-07-29 08:26 UTC, bigdatasourav commented on oci-test/tests/oci_mysql_configuration/variables.tf
> +  path         = "${path.cwd}/output.json"
Fix this space issue

2021-07-29 08:28 UTC, bigdatasourav commented on oci/service.go
> +	MySQLaasClient                 mysql.MysqlaasClient
```suggestion
	MySQLConfigurationClient                 mysql.MysqlaasClient
```

2021-07-29 08:28 UTC, bigdatasourav commented on oci/service.go
> +func mySQLaasService(ctx context.Context, d *plugin.QueryData, region string) (*session, error) {
can we name the service mySQLConfigurationService

2021-07-29 08:29 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +				Description: "The Configuration type, DEFAULT or CUSTOM..",
```suggestion
				Description: "The Configuration type, DEFAULT or CUSTOM.",
```

2021-07-29 08:29 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +				Description: "The current state of the Configuration",
```suggestion
				Description: "The current state of the Configuration.",
```

2021-07-29 08:29 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +				Description: "The current state of the Configuration",
```suggestion
				Description: "The current state of the Configuration.",
```

2021-07-29 08:33 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +				Description: "ConfigurationVariables User controllable service variables.",
```suggestion
				Description: "User controllable service variables of the Configuration.",
```

2021-07-29 08:34 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +				Description: "Time that budget was created.",
correct the description.

2021-07-29 08:35 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +		if strings.TrimSpace(id) == "" {
we can have this empty check outside if else block

2021-07-29 08:36 UTC, bigdatasourav requested changes
@rajeshbal65 suggested some changes.

2021-07-29 08:58 UTC, bigdatasourav commented on oci/service.go
> +// mySQLConfigurationService returns the service client for OCI MySQL aac Service
```suggestion
// mySQLConfigurationService returns the service client for OCI MySQL Configuration Service
```

2021-07-29 08:58 UTC, bigdatasourav commented on oci/service.go
> +	serviceCacheKey := fmt.Sprintf("mySQLaas-%s", region)
```suggestion
	serviceCacheKey := fmt.Sprintf("mysqlconfiguration-%s", region)
```

2021-07-29 10:41 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +			Hydrate:    getConfiguration,
```suggestion
			Hydrate:    getMySQLConfiguration,
```

2021-07-29 10:42 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +func configurationTags(ctx context.Context, d *transform.TransformData) (interface{}, error) {
```suggestion
func mySQLConfigurationTags(ctx context.Context, d *transform.TransformData) (interface{}, error) {
```

2021-08-21 07:14 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration.go
> +				Description: ColumnDescriptionCompartment,
compartment ID will be tenant ID in this table.

2021-08-21 07:23 UTC, bigdatasourav commented on docs/tables/oci_mysql_configuration.md
> +### List deleted configurations
remove this example, as for standard ones you will not get deleted.

2021-08-24 07:09 UTC, bigdatasourav approved these changes
LGTM

2021-08-24 07:13 UTC, rajlearner17 approved these changes
LGTM

2021-08-24 07:33 UTC, merged