Add table oci_core_network_public_ip_pool. Closes #180
turbot/steampipe-plugin-oci pull request #260
Opened 2021-07-28 11:19 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Test names: [ 'tests/oci_core_public_ip_pool' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_core_public_ip_pool []

PRETEST: tests/oci_core_public_ip_pool

TEST: tests/oci_core_public_ip_pool
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oci_core_public_ip_pool.named_test_resource will be created
  + resource "oci_core_public_ip_pool" "named_test_resource" {
      + cidr_blocks    = (known after apply)
      + compartment_id = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
      + defined_tags   = (known after apply)
      + display_name   = "steampipetest974"
      + freeform_tags  = {
          + "Name" = "steampipetest974"
        }
      + id             = (known after apply)
      + state          = (known after apply)
      + time_created   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + freeform_tags   = {
      + "Name" = "steampipetest974"
    }
  + lifecycle_state = (known after apply)
  + region          = "ap-mumbai-1"
  + resource_id     = (known after apply)
  + resource_name   = "steampipetest974"
  + tenancy_ocid    = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
oci_core_public_ip_pool.named_test_resource: Creating...
oci_core_public_ip_pool.named_test_resource: Creation complete after 2s [id=ocid1.publicippool.oc1.ap-mumbai-1.amaaaaaa6igdexaac2igqw4nbjvurn5xkux4srrxyjii6lmxfr4olnaxhk6q]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

freeform_tags = tomap({
  "Name" = "steampipetest974"
})
lifecycle_state = "ACTIVE"
region = "ap-mumbai-1"
resource_id = "ocid1.publicippool.oc1.ap-mumbai-1.amaaaaaa6igdexaac2igqw4nbjvurn5xkux4srrxyjii6lmxfr4olnaxhk6q"
resource_name = "steampipetest974"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"

Running SQL query: test-get-query.sql

[
  {
    "display_name": "steampipetest974",
    "freeform_tags": {
      "Name": "steampipetest974"
    },
    "id": "ocid1.publicippool.oc1.ap-mumbai-1.amaaaaaa6igdexaac2igqw4nbjvurn5xkux4srrxyjii6lmxfr4olnaxhk6q",
    "lifecycle_state": "ACTIVE"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "steampipetest974",
    "freeform_tags": {
      "Name": "steampipetest974"
    },
    "id": "ocid1.publicippool.oc1.ap-mumbai-1.amaaaaaa6igdexaac2igqw4nbjvurn5xkux4srrxyjii6lmxfr4olnaxhk6q",
    "lifecycle_state": "ACTIVE"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "steampipetest974"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_public_ip_pool

TEARDOWN: tests/oci_core_public_ip_pool

SUMMARY:

1/1 passed.cd 
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
+--------------+-------------------------------------------------------------------------------------------------+--------+---------------------+-------------+
| display_name | id                                                                                              | state  | time_created        | region      |
+--------------+-------------------------------------------------------------------------------------------------+--------+---------------------+-------------+
| test         | ocid1.publicippool.oc1.ap-mumbai-1.amaaaaaa6igdexaasjtzyk4xr7ia4ce4pvflt5hdtvjexjfczktq464cs2ea | ACTIVE | 2021-07-28 10:56:25 | ap-mumbai-1 |
| test         | ocid1.publicippool.oc1.ap-mumbai-1.amaaaaaa6igdexaa44zojv4aee3xqpg5uvsxp7ufhxi7gyon7q2nermts6aa | ACTIVE | 2021-07-28 09:36:11 | ap-mumbai-1 |
+--------------+-------------------------------------------------------------------------------------------------+--------+---------------------+-------------+
```
</details>

2021-07-29 08:49 UTC, bigdatasourav commented on docs/tables/oci_core_public_ip_pool.md
> +
can we add more examples

2021-07-29 08:49 UTC, bigdatasourav commented on oci/table_oci_core_public_ip_pool.go
> +				Description: "The OCID of the public IP pool..",
```suggestion
				Description: "The OCID of the public IP pool.",
```

2021-07-29 08:50 UTC, bigdatasourav commented on oci/table_oci_core_public_ip_pool.go
> +				Name:        "cidr_blocks",
json columns will be in last

2021-07-29 08:51 UTC, bigdatasourav commented on oci/table_oci_core_public_ip_pool.go
> +				Description: "The public IP pool's current state.",
description is not correct

2021-07-29 08:54 UTC, bigdatasourav commented on oci/table_oci_core_public_ip_pool.go
> +	// handle empty snapshot id in get call
```suggestion
	// handle empty public ip pool id in get call
```

2021-07-29 08:55 UTC, bigdatasourav requested changes
@rajeshbal65 some suggested changes.

2021-07-29 10:44 UTC, bigdatasourav commented on oci-test/tests/oci_core_public_ip_pool/variables.tf
> +
```suggestion
```

2021-07-29 15:50 UTC, bigdatasourav approved these changes
LGTM

2021-08-05 15:24 UTC, rajlearner17 approved these changes
LGTM

2021-08-06 10:47 UTC, merged