v0.1.0 closes #265
turbot/steampipe-plugin-oci pull request #266
Opened 2021-08-04 15:25 UTC by bigdatasourav

2021-08-04 18:03 UTC, cbruno10 requested changes
Please see comments, thanks!

2021-08-04 18:03 UTC, cbruno10 commented on CHANGELOG.md
> +- Fixed: Restrict get api call only to root compartment and one zone per region ([#264](https://github.com/turbot/steampipe-plugin-oci/pull/264))
```suggestion
- Fixed: Restrict get API calls to the root compartment and one zone per region in several core and file storage tables ([#264](https://github.com/turbot/steampipe-plugin-oci/pull/264))
```

We can add a bit more information here to let users know what types of tables are affected. Also `API` should be capitalized.

2021-08-04 18:03 UTC, cbruno10 commented on CHANGELOG.md
> +## v0.1.0 [2021-08-04]
When releasing, please remember to update this date

2021-08-06 11:17 UTC, rajlearner17 approved these changes
LGTM

2021-08-06 13:16 UTC, cbruno10 approved these changes

2021-08-06 13:30 UTC, merged