Add table oci_mysql_configuration_custom. Closes #274
turbot/steampipe-plugin-oci pull request #285
Opened 2021-08-18 10:22 UTC by c0d3r-arnab

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
arnab@turbotindias-MacBook-Pro oci-test % ./tint.js oci_mysql_configuration_custom
Test names: [ 'tests/oci_mysql_configuration_custom' ]
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_mysql_configuration_custom []

PRETEST: tests/oci_mysql_configuration_custom

TEST: tests/oci_mysql_configuration_custom
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.local_file.configuration will be read during apply
  # (config refers to values not yet known)
 <= data "local_file" "configuration"  {
      + content        = (known after apply)
      + content_base64 = (known after apply)
      + filename       = "/private/var/folders/df/957ty4t146vfy54wm4254kp40000gp/T/tests/oci_mysql_configuration_custom/terraform/test/output.json"
      + id             = (known after apply)
    }

  # null_resource.named_test_resource will be created
  + resource "null_resource" "named_test_resource" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + lifecycle_state = (known after apply)
  + region          = "ap-mumbai-1"
  + resource_id     = (known after apply)
  + resource_name   = (known after apply)
  + shape_name      = (known after apply)
  + tenancy_ocid    = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
  + type            = (known after apply)
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "oci mysql configuration create --compartment-id ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq --shape-name VM.Standard.E2.1 --output json > /private/var/folders/df/957ty4t146vfy54wm4254kp40000gp/T/tests/oci_mysql_configuration_custom/terraform/test/output.json"]
null_resource.named_test_resource (local-exec): WARNING: Permissions on /Users/arnab/.oci/config are too open.
null_resource.named_test_resource (local-exec): To fix this please try executing the following command:
null_resource.named_test_resource (local-exec): oci setup repair-file-permissions --file /Users/arnab/.oci/config
null_resource.named_test_resource (local-exec): Alternatively to hide this warning, you may set the environment variable, OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING:
null_resource.named_test_resource (local-exec): export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True

null_resource.named_test_resource (local-exec): WARNING: Permissions on /Users/arnab/PEM/-08-12-10-19.pem are too open.
null_resource.named_test_resource (local-exec): To fix this please try executing the following command:
null_resource.named_test_resource (local-exec): oci setup repair-file-permissions --file /Users/arnab/PEM/-08-12-10-19.pem
null_resource.named_test_resource (local-exec): Alternatively to hide this warning, you may set the environment variable, OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING:
null_resource.named_test_resource (local-exec): export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True

null_resource.named_test_resource: Creation complete after 1s [id=4935311508337421391]
data.local_file.configuration: Reading...
data.local_file.configuration: Read complete after 0s [id=763df05a117504129578aa68c64e5d21497c5297]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

lifecycle_state = "ACTIVE"
region = "ap-mumbai-1"
resource_id = "ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaolpvpcmyqbtqmdg6cxz6pienw3sxexxk3rix3ke4nutqia5o6mma"
resource_name = "mysqlconfiguration20210818102035"
shape_name = "VM.Standard.E2.1"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
type = "CUSTOM"

Running SQL query: test-get-query.sql

[
  {
    "display_name": "mysqlconfiguration20210818102035",
    "id": "ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaolpvpcmyqbtqmdg6cxz6pienw3sxexxk3rix3ke4nutqia5o6mma",
    "lifecycle_state": "ACTIVE",
    "shape_name": "VM.Standard.E2.1",
    "type": "CUSTOM"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "mysqlconfiguration20210818102035",
    "id": "ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaolpvpcmyqbtqmdg6cxz6pienw3sxexxk3rix3ke4nutqia5o6mma",
    "lifecycle_state": "ACTIVE",
    "shape_name": "VM.Standard.E2.1",
    "type": "CUSTOM"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "mysqlconfiguration20210818102035"
  }
]
✔ PASSED

POSTTEST: tests/oci_mysql_configuration_custom

TEARDOWN: tests/oci_mysql_configuration_custom

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  display_name,
  id,
  description,
  lifecycle_state as state,
  time_created
from
  oci_mysql_configuration_custom;
+----------------------------------+-------------------------------------------------------------------------------------------------------+-------------+---------+---------------------+
| display_name                     | id                                                                                                    | description | state   | time_created        |
+----------------------------------+-------------------------------------------------------------------------------------------------------+-------------+---------+---------------------+
| mysqlconfiguration20210727122951 | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaz2rl7gidlvihyhuljvdlaiqrsjdcfxa3ntdmluvhncguz2yacxda | <null>      | DELETED | 2021-07-27 12:29:51 |
| mysql20210729160050              | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaa4byx63at5pimfybveoouevzqh7b3gqpcnb5cy2kjo4ardxdbkmiq | <null>      | DELETED | 2021-07-29 10:30:59 |
| test1234                         | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaajrbxtmn2f7xc5oycal4acr2hxd2rrvihxia255rf5f5vhbjtr6ha | testing     | DELETED | 2021-07-08 05:23:49 |
| mysqlconfiguration20210727122458 | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaf46aywfgzdnxkjak3hgd5a6cbeowrmlpacqjhet6qaiwshvi6uhq | <null>      | DELETED | 2021-07-27 12:24:58 |
| mysqlconfiguration20210727115509 | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaawa3d6nim6c6tfhauyanwt2qtn7u43ru533mc4vtse5fuhm7beqsq | <null>      | DELETED | 2021-07-27 11:55:09 |
| mysqlconfiguration20210727122102 | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaanhsfpcshz4hbb7wjf3ij2ry45shk6ycl3levfoudkijqofnyj5ra | <null>      | DELETED | 2021-07-27 12:21:02 |
| mysqlconfiguration20210727123149 | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaaka7pgbosxniagxkxbyuasofssnfwzbifjphho4tvzgfezsagd32a | <null>      | DELETED | 2021-07-27 12:31:49 |
| mysqlconfiguration20210818101556 | ocid1.mysqlconfiguration.oc1.ap-mumbai-1.aaaaaaaavpyzlerwcvmnwlk47qta545fw36dqqe3wr4cspiwls3k2sqh2isq | <null>      | ACTIVE  | 2021-08-18 10:15:56 |
| mysqlconfiguration20210818081915 | ocid1.mysqlconfiguration.oc1.iad.aaaaaaaayt7z3otdamxawk2woqyjjwdt3aanc63joonmljqapu4uoibfiroa         | <null>      | ACTIVE  | 2021-08-18 08:19:15 |
| mysqlconfiguration20210818101436 | ocid1.mysqlconfiguration.oc1.iad.aaaaaaaagwbycssq5ehecezdawphsjensbii3copn2vsaws5brtthkmuc7nq         | <null>      | ACTIVE  | 2021-08-18 10:14:36 |
| mysqlconfiguration20210818101059 | ocid1.mysqlconfiguration.oc1.iad.aaaaaaaardtn7gkaj7mfjbwz2xzd5lqhaqzpxs3lkxczwu7swigh6jtz3kga         | <null>      | ACTIVE  | 2021-08-18 10:10:59 |
| m [...]

2021-08-21 07:15 UTC, bigdatasourav commented on docs/tables/oci_mysql_configuration.md
> +DB System configurations are collections of variables which define the operation of the MySQL DB System.
Updated the description as I already provided.

2021-08-21 07:17 UTC, bigdatasourav commented on docs/tables/oci_mysql_configuration_custom.md
> +Configurations have a default set of variables assigned to them, user and system variables. To add variables, you must create a new configuration with the desired variable definitions, or copy an exi
```suggestion
Configurations have a default set of variables assigned to them, user and system variables. To add variables, you must create a new configuration which will be a custom configuration with the desired variable definitions, or copy an existing configuration, edit it accordingly, and edit the DB System to use the new configuration.
```

2021-08-21 07:17 UTC, bigdatasourav commented on docs/tables/oci_mysql_configuration.md
> +DB System configurations are collections of variables which define the operation of the MySQL DB System.
remove oci_mysql_configuration table changes from this PR.

2021-08-21 07:18 UTC, bigdatasourav commented on oci/plugin.go
> +			"oci_mysql_configuration_custom":                                    tableMySQLCustomConfiguration(ctx),
```suggestion
			"oci_mysql_configuration_custom":                                    tableMySQLConfigurationCustom(ctx),
```

2021-08-21 07:20 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration_custom.go
> +                Description: "The display name of the Configuration.",
```suggestion
                Description: "The display name of the configuration.",
```

2021-08-21 07:20 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration_custom.go
> +                Description: "The OCID of the Configuration.",
```suggestion
                Description: "The OCID of the configuration.",
```

2021-08-21 07:20 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration_custom.go
> +                Description: "The OCID of the Configuration from which this Configuration is derived.",
```suggestion
                Description: "The OCID of the configuration from which this configuration is derived.",
```

2021-08-21 07:21 UTC, bigdatasourav commented on oci/table_oci_mysql_configuration_custom.go
> +                Description: "The name of the associated Shape.",
```suggestion
                Description: "The name of the associated shape.",
```

2021-08-21 07:22 UTC, bigdatasourav requested changes
@c0d3r-arnab Please check the suggested changes

2021-08-24 08:46 UTC, bigdatasourav commented on oci-test/tests/oci_mysql_configuration_custom/variables.tf
> +    command = "oci mysql configuration create --compartment-id ${var.tenancy_ocid} --shape-name ${var.shape} --output json > ${local.path}"
Add Post-test to delete the resource as you are using CLI here, TF will not delete it.

2021-08-24 10:51 UTC, bigdatasourav approved these changes
LGTM

2021-08-25 06:53 UTC, rajlearner17 approved these changes
LGTM

2021-08-25 06:53 UTC, merged