Add table oci_database_software_image. Closes #289
turbot/steampipe-plugin-oci pull request #291
Opened 2021-08-19 15:04 UTC by c0d3r-arnab

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Test names: [ 'tests/oci_database_software_image' ]
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_database_software_image []

PRETEST: tests/oci_database_software_image

TEST: tests/oci_database_software_image
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oci_database_database_software_image.named_test_resource will be created
  + resource "oci_database_database_software_image" "named_test_resource" {
      + compartment_id                           = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
      + database_software_image_included_patches = (known after apply)
      + database_software_image_one_off_patches  = (known after apply)
      + database_version                         = "19.0.0.0"
      + defined_tags                             = (known after apply)
      + display_name                             = "steampipetest6694"
      + freeform_tags                            = {
          + "Name" = "steampipetest6694"
        }
      + id                                       = (known after apply)
      + image_shape_family                       = (known after apply)
      + image_type                               = "DATABASE_IMAGE"
      + included_patches_summary                 = (known after apply)
      + is_upgrade_supported                     = (known after apply)
      + lifecycle_details                        = (known after apply)
      + ls_inventory                             = (known after apply)
      + patch_set                                = "19.11.0.0"
      + source_db_home_id                        = (known after apply)
      + state                                    = (known after apply)
      + time_created                             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + database_version = "19.0.0.0"
  + image_type       = "DATABASE_IMAGE"
  + patch_set        = "19.11.0.0"
  + resource_id      = (known after apply)
  + resource_name    = "steampipetest6694"
  + tenancy_ocid     = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
oci_database_database_software_image.named_test_resource: Creating...
oci_database_database_software_image.named_test_resource: Still creating... [10s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [20s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [30s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [40s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [50s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [1m0s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [1m10s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [1m20s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [1m30s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [1m40s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [1m50s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [2m0s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [2m10s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [2m20s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [2m30s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [5m15s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [5m25s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [5m35s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [5m45s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [5m55s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [6m5s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [6m15s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [6m25s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [6m35s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [6m45s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [6m55s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [7m5s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [7m15s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [7m25s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [7m35s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [7m45s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [7m55s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [8m5s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [8m15s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [8m25s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [8m35s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [8m45s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [8m55s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [10m12s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [10m22s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [10m32s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [10m42s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [10m52s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [11m2s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [11m12s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [11m22s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [11m32s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [11m42s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [11m52s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [12m2s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [12m12s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [12m22s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [13m52s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [14m2s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [14m12s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [14m22s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [14m32s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [14m42s elapsed]
oci_database_database_software_image.named_test_resource: Still creating... [14m52s elapsed]
oci_databa [...]

2021-08-21 07:26 UTC, bigdatasourav commented on oci/plugin.go
> +			"oci_database_software_image":                                  	 tableOciDatabaseSoftwareImage(ctx),
Indentation is not proper

2021-08-21 07:26 UTC, bigdatasourav commented on oci/table_oci_database_software_image.go
> +				Description: "The type of software image. Can be grid or database.",
```suggestion
				Description: "The type of software image. It can be grid or database.",
```

2021-08-21 07:27 UTC, bigdatasourav commented on oci/table_oci_database_software_image.go
> +				Description: "The PSU or PBP or Release Updates.",
```suggestion
				Description: "The PSU or PBP or release updates.",
```

2021-08-21 07:28 UTC, bigdatasourav commented on oci/table_oci_database_software_image.go
> +				Description: "True if this Database software image is supported for Upgrade.",
```suggestion
				Description: "True, if this database software image is supported for upgrade.",
```

2021-08-21 07:28 UTC, bigdatasourav commented on oci/table_oci_database_software_image.go
> +				Description: "List of one-off patches for Database Homes.",
```suggestion
				Description: "List of one-off patches for database homes.",
```

2021-08-21 07:28 UTC, bigdatasourav commented on oci/table_oci_database_software_image.go
> +				Description: "List of one-off patches for Database Homes.",
```suggestion
				Description: "List of one-off patches for database homes.",
```

2021-08-21 07:33 UTC, bigdatasourav commented on oci/table_oci_database_software_image.go
> +				Name:        "included_patches",
why the column name is sort and not as per the API response.

2021-08-21 07:34 UTC, bigdatasourav requested changes
@c0d3r-arnab Please check the suggested changes.

2021-08-24 07:56 UTC, bigdatasourav approved these changes
LGTM

2021-08-24 07:58 UTC, rajlearner17 approved these changes
LGTM

2021-08-24 08:43 UTC, merged