Add table oci_vault_secret. Closes #337
turbot/steampipe-plugin-oci pull request #343
Opened 2022-01-17 13:52 UTC by c0d3r-arnab

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
arnab@turbotindias-MacBook-Pro oci-test % ./tint.js oci_vault_secret
Test names: [ 'tests/oci_vault_secret' ]
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_vault_secret []

PRETEST: tests/oci_vault_secret
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.local_file.secret will be read during apply
  # (config refers to values not yet known)
 <= data "local_file" "secret"  {
      + content        = (known after apply)
      + content_base64 = (known after apply)
      + filename       = "/private/var/folders/df/957ty4t146vfy54wm4254kp40000gp/T/tests/oci_vault_secret/terraform/pretest/output.json"
      + id             = (known after apply)
    }

  # null_resource.named_test_resource will be created
  + resource "null_resource" "named_test_resource" {
      + id = (known after apply)
    }

  # oci_kms_key.named_test_resource will be created
  + resource "oci_kms_key" "named_test_resource" {
      + compartment_id       = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
      + current_key_version  = (known after apply)
      + defined_tags         = (known after apply)
      + desired_state        = (known after apply)
      + display_name         = "steampipetest7312"
      + freeform_tags        = (known after apply)
      + id                   = (known after apply)
      + is_primary           = (known after apply)
      + management_endpoint  = (known after apply)
      + protection_mode      = (known after apply)
      + replica_details      = (known after apply)
      + restored_from_key_id = (known after apply)
      + state                = (known after apply)
      + time_created         = (known after apply)
      + time_of_deletion     = (known after apply)
      + vault_id             = (known after apply)

      + key_shape {
          + algorithm = "AES"
          + curve_id  = (known after apply)
          + length    = 16
        }
    }

  # oci_kms_vault.named_test_resource will be created
  + resource "oci_kms_vault" "named_test_resource" {
      + compartment_id         = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
      + crypto_endpoint        = (known after apply)
      + defined_tags           = (known after apply)
      + display_name           = "steampipetest7312"
      + freeform_tags          = (known after apply)
      + id                     = (known after apply)
      + is_primary             = (known after apply)
      + management_endpoint    = (known after apply)
      + replica_details        = (known after apply)
      + restored_from_vault_id = (known after apply)
      + state                  = (known after apply)
      + time_created           = (known after apply)
      + time_of_deletion       = (known after apply)
      + vault_type             = "DEFAULT"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + lifecycle_state = (known after apply)
  + resource_id     = (known after apply)
  + resource_name   = "steampipetest7312"
  + tenancy_ocid    = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
oci_kms_vault.named_test_resource: Creating...
oci_kms_vault.named_test_resource: Still creating... [10s elapsed]
oci_kms_vault.named_test_resource: Still creating... [20s elapsed]
oci_kms_vault.named_test_resource: Still creating... [30s elapsed]
oci_kms_vault.named_test_resource: Still creating... [40s elapsed]
oci_kms_vault.named_test_resource: Still creating... [50s elapsed]
oci_kms_vault.named_test_resource: Still creating... [1m0s elapsed]
oci_kms_vault.named_test_resource: Still creating... [1m10s elapsed]
oci_kms_vault.named_test_resource: Still creating... [1m20s elapsed]
oci_kms_vault.named_test_resource: Still creating... [1m30s elapsed]
oci_kms_vault.named_test_resource: Still creating... [1m40s elapsed]
oci_kms_vault.named_test_resource: Still creating... [1m50s elapsed]
oci_kms_vault.named_test_resource: Still creating... [2m0s elapsed]
oci_kms_vault.named_test_resource: Still creating... [2m10s elapsed]
oci_kms_vault.named_test_resource: Still creating... [2m20s elapsed]
oci_kms_vault.named_test_resource: Still creating... [2m30s elapsed]
oci_kms_vault.named_test_resource: Still creating... [2m40s elapsed]
oci_kms_vault.named_test_resource: Still creating... [2m50s elapsed]
oci_kms_vault.named_test_resource: Still creating... [3m0s elapsed]
oci_kms_vault.named_test_resource: Still creating... [3m10s elapsed]
oci_kms_vault.named_test_resource: Still creating... [3m20s elapsed]
oci_kms_vault.named_test_resource: Still creating... [3m30s elapsed]
oci_kms_vault.named_test_resource: Still creating... [3m40s elapsed]
oci_kms_vault.named_test_resource: Still creating... [3m50s elapsed]
oci_kms_vault.named_test_resource: Still creating... [4m0s elapsed]
oci_kms_vault.named_test_resource: Still creating... [4m10s elapsed]
oci_kms_vault.named_test_resource: Still creating... [4m20s elapsed]
oci_kms_vault.named_test_resource: Still creating... [4m30s elapsed]
oci_kms_vault.named_test_resource: Still creating... [4m40s elapsed]
oci_kms_vault.named_test_resource: Still creating... [4m50s elapsed]
oci_kms_vault.named_test_resource: Still creating... [5m0s elapsed]
oci_kms_vault.named_test_resource: Still creating... [5m10s elapsed]
oci_kms_vault.named_test_resource: Still creating... [5m20s elapsed]
oci_kms_vault.named_test_resource: Still creating... [5m30s elapsed]
oci_kms_vault.named_test_resource: Still creating... [5m40s elapsed]
oci_kms_vault.named_test_resource: Still creating... [5m50s elapsed]
oci_kms_vault.named_test_resource: Still creating... [6m0s elapsed]
oci_kms_vault.named_test_resource: Still creating... [6m10s elapsed]
oci_kms_vault.named_test_resource: Still creating... [6m20s elapsed]
oci_kms_vault.named_test_resource: Creation complete after 6m27s [id=ocid1.vault.oc1.iad.b5q6k2lnaagn6.abuwcljsgyzbclulalrwon2ydrit6r4wlts22hnevhyx2kjhfvkh6yhfqs6q]
oci_kms_key.named_test_resource: Creating...
oci_kms_key.named_test_resource: Still creating... [10s elapsed]
oci_kms_key.named_test_resource: Still creating... [20s elapsed]
oci_kms_key.named_test_resource: Still creating... [30s elapsed]
oci_kms_key.named_test_resource: Still creating... [40s elapsed]
oci_kms_key.named_test_resource: Still creating... [50s elapsed]
oci_kms_key.named_test_resource: Still creating... [1m0s elapsed]
oci_kms_key.named_test_resource: Still creating... [1m10s elapsed]
oci_kms_key.named_test_resource: Still creating... [1m20s elapsed]
oci_kms_key.named_test_resource: Still creating... [1m30s elapsed]
oci_kms_key.named_test_resource: Still creating... [1m40s elapsed]
oci_kms_key.named_test_resource: Still creating... [1m50s elapsed]
oci_kms_key.named_test_resource: Still creating... [2m0s elapsed]
oci_kms_key.named_test_resource: Still creating... [2m10s elapsed]
oci_kms_key.named_test_resource: Still creating... [2m20s elapsed]
oci_kms_key.named_test_resource: Still creating... [2m30s elapsed]
oci_kms_key.named_test_resource: Still creating... [2m40s elapsed]
oci_kms_key.named_test_resource: Still creating... [2m50s elapsed]
oci_kms_key.named_test_resource: Still creating... [3m0s elapsed]
oci_kms_key.named_test_resource: Still creating... [3m10s elapsed]
oci_kms_key.named_test_resource: Still creating... [3m20s elapsed]
oci_kms_key.named_test_resource: Still creating... [3m30s elapsed]
oci_kms_key.named_test_resource: Still creating... [3m40s elapsed]
oci_kms_key.named_test_resource: Still creating... [3m50s elapsed]
oci_kms_key.named_test_resource: Still creating... [4m0s elapsed]
oci_kms_key.named_test_resource [...]

2022-01-17 14:40 UTC, bigdatasourav approved these changes
LGTM

2022-01-19 07:19 UTC, rajlearner17 requested changes
@c0d3r-arnab 
revisit descriptions as discussed

2022-01-19 07:36 UTC, misraved commented on oci/table_oci_vault_secret.go
> +				Description: "The version number of the secret version that's currently in use.",
```suggestion
				Description: "The version number of the secret that's currently in use.",
```

2022-01-19 07:36 UTC, misraved commented on oci/table_oci_vault_secret.go
> +				Description: "n optional property indicating when to delete the secret.",
```suggestion
				Description: "An optional property indicating when to delete the secret.",
```

2022-01-19 07:38 UTC, misraved reviewed
Make changes to the descriptions of the suggested columns

2022-01-19 08:51 UTC, rajlearner17 approved these changes
Looks good after testing required changes.

2022-01-19 10:04 UTC, merged