Add table oci_ons_subscription. Closes #38
turbot/steampipe-plugin-oci pull request #43
Opened 2021-04-06 12:31 UTC by visiit

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
vishalkumar@Vishals-Air oci-test % TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq ./tint.js tests/oci_ons_subscription
Test names: [ 'tests/oci_ons_subscription' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
SETUP: tests/oci_ons_subscription []
PRETEST: tests/oci_ons_subscription
TEST: tests/oci_ons_subscription
Running terraform
oci_identity_group.test_group: Creating...
oci_identity_group.test_group: Creation complete after 4s [id=ocid1.group.oc1..aaaaaaaaqew5uoqaibikpohik2majzgyi4qicco5g76zlabopzj7vr24anrq]
oci_ons_notification_topic.named_test_resource: Creating...
oci_ons_notification_topic.named_test_resource: Creation complete after 2s [id=ocid1.onstopic.oc1.ap-mumbai-1.aaaaaaaakv5ezpfotiq7lrcfadpblepmsqytlk3ae5m5argt4siwkcizmqfa]
oci_ons_subscription.named_test_resource: Creating...
oci_ons_subscription.named_test_resource: Creation complete after 0s [id=ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaav33f67tqxzinalk3ez6hilz552ivgpzznv7yjssqsnhrh2264peq]
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
Outputs:
created_time = 1617708457591
endpoint = test@gmail.com
etag = e50c0119
lifecycle_state = PENDING
protocol = EMAIL
resource_id = ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaav33f67tqxzinalk3ez6hilz552ivgpzznv7yjssqsnhrh2264peq
resource_name = steampipetest6078
tenancy_ocid = ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq
Running SQL query: test-get-query.sql
[
  {
    "endpoint": "test@gmail.com",
    "etag": "e50c0119",
    "freeform_tags": {
      "Name": "steampipetest6078"
    },
    "id": "ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaav33f67tqxzinalk3ez6hilz552ivgpzznv7yjssqsnhrh2264peq",
    "protocol": "EMAIL"
  }
]
✔ PASSED
Running SQL query: test-list-query.sql
[
  {
    "endpoint": "test@gmail.com",
    "freeform_tags": {
      "Name": "steampipetest6078"
    },
    "id": "ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaav33f67tqxzinalk3ez6hilz552ivgpzznv7yjssqsnhrh2264peq",
    "lifecycle_state": "PENDING",
    "protocol": "EMAIL"
  }
]
✔ PASSED
Running SQL query: test-not-found-query.sql
null
✔ PASSED
Running SQL query: test-turbot-query.sql
[
  {
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
  }
]
✔ PASSED
POSTTEST: tests/oci_ons_subscription
TEARDOWN: tests/oci_ons_subscription
SUMMARY:
1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
- Basic info

select
  id,
  topic_id,
  lifecycle_state,
  protocol,
  endpoint,
  etag
from
  oci_ons_subscription;

+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-----------------+----------+-------------------+----------+
| id                                                                                                 | topic_id                                                                                    | lifecycle_state | protocol | endpoint          | etag     |
+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-----------------+----------+-------------------+----------+
| ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaap57juvblbjgzcddis37gxummh3voqsou54n7eoymkz33qeltbohq | ocid1.onstopic.oc1.ap-mumbai-1.aaaaaaaatf7hm4tpbz5eyf5mouhqsdvugu5qf7c5s74ftzgvgwkbvucbewqa | PENDING         | EMAIL    | vishal@turbot.com | 10be645e |
+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-----------------+----------+-------------------+----------+

- Get details of specific subscription

select
  id,
  topic_id,
  lifecycle_state,
  etag,
  freeform_tags,
  delivery_policy
from
  oci_ons_subscription
where
  id = 'ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaap57juvblbjgzcddis37gxummh3voqsou54n7eoymkz38uyhbgfdc';

+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-----------------+----------+---------------+-----------------+
| id                                                                                                 | topic_id                                                                                    | lifecycle_state | etag     | freeform_tags | delivery_policy |
+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-----------------+----------+---------------+-----------------+
| ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaap57juvblbjgzcddis37gxummh3voqsou54n7eoymkz33qeltbohq | ocid1.onstopic.oc1.ap-mumbai-1.aaaaaaaatf7hm4tpbz5eyf5mouhqsdvugu5qf7c5s74ftzgvgwkbvucbewqa | PENDING         | 10be645e | {}            | <null>          |
+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+-----------------+----------+---------------+-----------------+

-  List of subscription where state is pending

select
  id,
  lifecycle_state,
  protocol,
  endpoint
from
  oci_ons_subscription
where
  lifecycle_state = 'PENDING';

+----------------------------------------------------------------------------------------------------+-----------------+----------+-------------------+
| id                                                                                                 | lifecycle_state | protocol | endpoint          |
+----------------------------------------------------------------------------------------------------+-----------------+----------+-------------------+
| ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaap57juvblbjgzcddis37gxummh3voqsou54n7eoymkz33qeltbohq | PENDING         | EMAIL    | vishal@turbot.com |
+----------------------------------------------------------------------------------------------------+-----------------+----------+-------------------+
```
</details>

2021-04-08 10:25 UTC, khushboo9024 commented on oci/service.go
> +func notificationDataPlaneService(ctx context.Context, d *plugin.QueryData, region string) (*session, error) {
Function name is not correct.

2021-04-08 10:28 UTC, khushboo9024 commented on oci/table_oci_ons_subscription.go
> +			{
JSON columns should come after the string columns

2021-04-08 10:29 UTC, khushboo9024 commented on oci/table_oci_ons_subscription.go
> +				Name:        "topic_id",
`topic_id` is important , this should be the third column.

2021-04-08 10:39 UTC, khushboo9024 commented on oci/table_oci_ons_subscription.go
> +			{
Add region column here.

2021-04-15 14:39 UTC, khushboo9024 commented on oci/service.go
> +// onsNotificationDataPlaneService returns the service client for OCI Core Notification service
```suggestion
// onsNotificationDataPlaneService returns the service client for OCI Notification Data Plane service
```

2021-04-15 14:40 UTC, khushboo9024 commented on oci/service.go
> +func onsNotificationDataPlaneService(ctx context.Context, d *plugin.QueryData, region string) (*session, error) {
This service name is different from the one used in topic?

2021-04-16 06:58 UTC, khushboo9024 commented on docs/tables/oci_ons_subscription.md
> +### List of subscription where state is pending
```suggestion
### List subscriptions in pending state
```

2021-04-16 07:57 UTC, khushboo9024 approved these changes
LGTM

2021-04-22 06:12 UTC, visiit commented on oci/table_oci_ons_subscription.go
> +				Type:        proto.ColumnType_INT,
@LalitTurbot In `SDK` there is a problem with  `CreatedTime` datatype.
```
// The time when this suscription was created.
	CreatedTime *int64 `mandatory:"false" json:"createdTime"`
```

2021-04-22 10:40 UTC, rajmohanty17 requested changes
Some solid example can be 
List the subscriptions by protocol type
List the subscriptions for which the Endpoint is not e.g. tutbot.com email domain

2021-04-22 12:26 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 19:26 UTC, cbruno10 approved these changes

2021-04-22 19:26 UTC, merged