Add table oci_core_service_gateway. Closes #48
turbot/steampipe-plugin-oci pull request #49
Opened 2021-04-07 14:09 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Test names: [ 'tests/oci_core_service_gateway' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_core_service_gateway []

PRETEST: tests/oci_core_service_gateway

TEST: tests/oci_core_service_gateway
Running terraform
oci_core_vcn.named_test_resource: Creating...
oci_core_vcn.named_test_resource: Creation complete after 1s [id=ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaasdgsvacejxpydbitm7c4rjcc3nqcpoabzteas4ciqs4a]
oci_core_route_table.named_test_resource: Creating...
oci_core_internet_gateway.test_internet_gateway: Creating...
oci_core_internet_gateway.test_internet_gateway: Creation complete after 0s [id=ocid1.internetgateway.oc1.ap-mumbai-1.aaaaaaaackkcvhtl6ip7prmypqwsutm4sszgmf6exzog6rxp5723o5eih6pq]
oci_core_route_table.named_test_resource: Creation complete after 1s [id=ocid1.routetable.oc1.ap-mumbai-1.aaaaaaaahcvsf7ke7rzlgtemtc44hkrce47df7rm5nolzcjfsz3izwneguwa]
oci_core_service_gateway.named_test_resource: Creating...
oci_core_service_gateway.named_test_resource: Creation complete after 2s [id=ocid1.servicegateway.oc1.ap-mumbai-1.aaaaaaaawkh7k4w63fyz3bdowzialb7t7l2fiocexs66uscsplnc2ez2zpea]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

block_traffic = false
freeform_tags = tomap({
  "Name" = "steampipetest4767"
})
region = "ap-mumbai-1"
resource_id = "ocid1.servicegateway.oc1.ap-mumbai-1.aaaaaaaawkh7k4w63fyz3bdowzialb7t7l2fiocexs66uscsplnc2ez2zpea"
resource_name = "steampipetest4767"
route_table_id = "ocid1.routetable.oc1.ap-mumbai-1.aaaaaaaahcvsf7ke7rzlgtemtc44hkrce47df7rm5nolzcjfsz3izwneguwa"
state = "AVAILABLE"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
vcn_id = "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaasdgsvacejxpydbitm7c4rjcc3nqcpoabzteas4ciqs4a"

Running SQL query: test-get-query.sql

[
  {
    "block_traffic": false,
    "display_name": "steampipetest4767",
    "freeform_tags": {
      "Name": "steampipetest4767"
    },
    "id": "ocid1.servicegateway.oc1.ap-mumbai-1.aaaaaaaawkh7k4w63fyz3bdowzialb7t7l2fiocexs66uscsplnc2ez2zpea",
    "route_table_id": "ocid1.routetable.oc1.ap-mumbai-1.aaaaaaaahcvsf7ke7rzlgtemtc44hkrce47df7rm5nolzcjfsz3izwneguwa",
    "vcn_id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaasdgsvacejxpydbitm7c4rjcc3nqcpoabzteas4ciqs4a"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "block_traffic": false,
    "display_name": "steampipetest4767",
    "freeform_tags": {
      "Name": "steampipetest4767"
    },
    "id": "ocid1.servicegateway.oc1.ap-mumbai-1.aaaaaaaawkh7k4w63fyz3bdowzialb7t7l2fiocexs66uscsplnc2ez2zpea",
    "route_table_id": "ocid1.routetable.oc1.ap-mumbai-1.aaaaaaaahcvsf7ke7rzlgtemtc44hkrce47df7rm5nolzcjfsz3izwneguwa",
    "vcn_id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaasdgsvacejxpydbitm7c4rjcc3nqcpoabzteas4ciqs4a"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "steampipetest4767"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_service_gateway

TEARDOWN: tests/oci_core_service_gateway

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
select
  display_name,
  id,
  time_created,
  vcn_id lifecycle_state,
  region
from
  oci_core_service_gateway;

+--------------+---------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------+-------------+
| display_name | id                                                                                                | time_created        | lifecycle_state                                                                        | region      |
+--------------+---------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------+-------------+
| efgr         | ocid1.servicegateway.oc1.ap-mumbai-1.aaaaaaaaqed5e4bipeybkujohunanvdf4ibtg4bve5dyjbm6q4xkh5svstga | 2021-04-07 13:57:58 | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaatw3zcb7y5bmzi23snukewp2tozurqp42bkcegx76cb2q | ap-mumbai-1 |
+--------------+---------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------------------+-------------+

select
  display_name,
  id,
  route_table_id
from
  oci_core_service_gateway;
+--------------+---------------------------------------------------------------------------------------------------+----------------+
| display_name | id                                                                                                | route_table_id |
+--------------+---------------------------------------------------------------------------------------------------+----------------+
| efgr         | ocid1.servicegateway.oc1.ap-mumbai-1.aaaaaaaaqed5e4bipeybkujohunanvdf4ibtg4bve5dyjbm6q4xkh5svstga | <null>         |
+--------------+---------------------------------------------------------------------------------------------------+----------------+
```
</details>

2021-04-08 11:29 UTC, khushboo9024 commented on docs/tables/oci_core_service_gateway.md
> +  vcn_id lifecycle_state,
syntax is wrong.

2021-04-08 11:31 UTC, khushboo9024 commented on oci-test/tests/oci_core_service_gateway/variables.tf
> +
Remove extra empty lines.

2021-04-08 11:34 UTC, khushboo9024 commented on oci-test/tests/oci_core_service_gateway/variables.tf
> +resource "oci_core_internet_gateway" "test_internet_gateway" {
Is this required?

2021-04-08 11:35 UTC, khushboo9024 commented on oci-test/tests/oci_core_service_gateway/variables.tf
> +  # route_rules {
Remove the commented lines and please put the resource blocks in the correct sequence.

2021-04-08 11:35 UTC, khushboo9024 commented on oci-test/tests/oci_core_service_gateway/variables.tf
> +
Remove extra line.

2021-04-08 11:35 UTC, khushboo9024 commented on oci-test/tests/oci_core_service_gateway/variables.tf
> +
Remove extra line.

2021-04-08 11:37 UTC, khushboo9024 commented on oci/table_oci_core_service_gateway.go
> +	logger.Debug("oci.listCoreNatGateways", "Compartment", compartment, "OCI_REGION", region)
```suggestion
	logger.Debug("oci. listCoreServiceGateways", "Compartment", compartment, "OCI_REGION", region)
```

2021-04-08 11:38 UTC, khushboo9024 commented on oci/table_oci_core_service_gateway.go
> +	plugin.Logger(ctx).Trace("getUser")
```suggestion
	plugin.Logger(ctx).Trace("getCoreServiceGateway")
```

2021-04-08 11:38 UTC, khushboo9024 commented on oci/table_oci_core_service_gateway.go
> +	logger.Debug("oci.getCoreNatGateway", "Compartment", compartment, "OCI_REGION", region)
```suggestion
	logger.Debug("oci. getCoreServiceGateway", "Compartment", compartment, "OCI_REGION", region)
```

2021-04-08 11:39 UTC, khushboo9024 commented on oci/table_oci_core_service_gateway.go
> +func serviceGatewayRegion(_ context.Context, d *transform.TransformData) (interface{}, error) {
This function will not give the correct region name, please change accordingly.

2021-04-08 11:45 UTC, khushboo9024 commented on docs/tables/oci_core_service_gateway.md
> +### List of Service gateways without application tag key
```suggestion
### List Service gateways without application tag key
```

2021-04-08 11:48 UTC, khushboo9024 commented on oci/table_oci_core_service_gateway.go
> +				Name:        "time_created",
Can you please keep `time_created` column as the sixth column.

2021-04-08 12:19 UTC, khushboo9024 commented on docs/tables/oci_core_service_gateway.md
> +### Services info that enabled for Service gateways
```suggestion
### List services which are enabled for service gateways
```

2021-04-09 10:28 UTC, khushboo9024 requested changes
Please make one small change in the document and also resolve the merge conflict.

2021-04-12 06:08 UTC, khushboo9024 commented on oci/table_oci_core_service_gateway.go
> +type serviceGatewayInfo struct {
Please use the new function ociRegionName for region column rather than using this custom struct.

2021-04-12 08:29 UTC, khushboo9024 approved these changes
LGTM

2021-04-16 07:30 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 20:11 UTC, merged