Fix index out of range error when regions config arg is not set
turbot/steampipe-plugin-oci pull request #537
Opened 2023-08-31 15:30 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2023-08-31 16:07 UTC, misraved commented on oci/multi_region.go
> +			if strings.Contains(err.Error(), "no such host") && endpointRegion != "" {
@bigdatasourav why are we adding the `endpointRegion != ""` check? Is it necessary?

2023-08-31 16:08 UTC, misraved commented
@bigdatasourav could you please add in example query results as well?

2023-08-31 16:30 UTC, cbruno10 requested changes
@bigdatasourav Please see comments, thanks!

2023-08-31 16:33 UTC, cbruno10 commented on oci/multi_region.go
> +	if GetConfig(d.Connection).Regions != nil {
For reference, the AWS plugin uses the "default" region to describe the regions (https://github.com/turbot/steampipe-plugin-aws/blob/fd736d30b83ccf7b9db4e6be45fd1deb86db08de/aws/multi_region.go#L446), I think we should do something similar here

2023-09-01 16:05 UTC, misraved approved these changes

2023-09-01 16:05 UTC, merged