Add table oci_core_security_list. Closes #47
turbot/steampipe-plugin-oci pull request #65
Opened 2021-04-09 08:26 UTC by visiit

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
vishalkumar@Vishals-Air oci-test % TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq ./tint.js tests/oci_core_security_list
Test names: [ 'tests/oci_core_security_list' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_core_security_list []

PRETEST: tests/oci_core_security_list

TEST: tests/oci_core_security_list
Running terraform
oci_identity_group.test_group: Creating...
oci_identity_group.test_group: Creation complete after 4s [id=ocid1.group.oc1..aaaaaaaa65csxldtmocxqyr5ocfj3kxmrbrme2zk3wz5t7rwnb7wtt2ke25a]
oci_core_vcn.named_test_resource: Creating...
oci_core_vcn.named_test_resource: Creation complete after 3s [id=ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaad3min2fq557unb4q5nhmiddr33zvpwepqqyi334pf3cq]
oci_core_security_list.named_test_resource: Creating...
oci_core_security_list.named_test_resource: Creation complete after 1s [id=ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaavjxrxcnjndus4lsn35diqaadcw4uxcxhgzyiuioerut4sk66acpa]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

region = ap-mumbai-1
resource_id = ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaavjxrxcnjndus4lsn35diqaadcw4uxcxhgzyiuioerut4sk66acpa
resource_name = steampipetest7753
tenancy_ocid = ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq
vcn_id = ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaad3min2fq557unb4q5nhmiddr33zvpwepqqyi334pf3cq

Running SQL query: test-get-query.sql

[
  {
    "display_name": "steampipetest7753",
    "freeform_tags": {
      "Name": "steampipetest7753"
    },
    "id": "ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaavjxrxcnjndus4lsn35diqaadcw4uxcxhgzyiuioerut4sk66acpa",
    "lifecycle_state": "AVAILABLE"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "steampipetest7753",
    "freeform_tags": {
      "Name": "steampipetest7753"
    },
    "id": "ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaavjxrxcnjndus4lsn35diqaadcw4uxcxhgzyiuioerut4sk66acpa",
    "lifecycle_state": "AVAILABLE",
    "vcn_id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaad3min2fq557unb4q5nhmiddr33zvpwepqqyi334pf3cq"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "steampipetest7753"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_security_list

TEARDOWN: tests/oci_core_security_list

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
- Basic info

select
  display_name,
  id,
  lifecycle_state,
  time_created,
  vcn_id
from
  oci_core_security_list;

+---------------------------------------------+-------------------------------------------------------------------------------------------------+-----------------+---------------------+----------------------------------------------------------------------------------------+
| display_name                                | id                                                                                              | lifecycle_state | time_created        | vcn_id                                                                                 |
+---------------------------------------------+-------------------------------------------------------------------------------------------------+-----------------+---------------------+----------------------------------------------------------------------------------------+
| test-steampipe-rule                         | ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaak6haggimwbffytlr72267dwzgv3pbps2t467winmu4nkeeqesz7q | AVAILABLE       | 2021-04-09 05:36:33 | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa24wsljja2vtzqod3j5rceq4svwyrjs2i56z254vvw55a |
| Default Security List for testVCN           | ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaaqdnjufa3iv3mifc7fg2zs36k2n6gnei6fxkmmsiestqf3yjxmbwq | AVAILABLE       | 2021-04-08 09:39:08 | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa24wsljja2vtzqod3j5rceq4svwyrjs2i56z254vvw55a |
| Default Security List for vcn-20210308-2057 | ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaazbkz4nqy4uujfrp7avql4bkavpequy7wnvnpxnzmbs3wwx4jt5yq | AVAILABLE       | 2021-03-08 15:28:02 | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa5x3ugencwrt5mfbuxf5rvzknpwsdy63mt5tz2xnzpjma |
| Default Security List for vcn-20210308-2057 | ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaazbkz4nqy4uujfrp7avql4bkavpequy7wnvnpxnzmbs3wwx4jt5yq | AVAILABLE       | 2021-03-08 15:28:02 | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa5x3ugencwrt5mfbuxf5rvzknpwsdy63mt5tz2xnzpjma |
| Default Security List for testVCN           | ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaaqdnjufa3iv3mifc7fg2zs36k2n6gnei6fxkmmsiestqf3yjxmbwq | AVAILABLE       | 2021-04-08 09:39:08 | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa24wsljja2vtzqod3j5rceq4svwyrjs2i56z254vvw55a |
| test-steampipe-rule                         | ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaak6haggimwbffytlr72267dwzgv3pbps2t467winmu4nkeeqesz7q | AVAILABLE       | 2021-04-09 05:36:33 | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa24wsljja2vtzqod3j5rceq4svwyrjs2i56z254vvw55a |
+---------------------------------------------+-------------------------------------------------------------------------------------------------+-----------------+---------------------+----------------------------------------------------------------------------------------+

-  Get a specific security list

select
  display_name,
  id,
  lifecycle_state,
  egress_security_rules,
  ingress_security_rules
from
  oci_core_security_list
where
  id = 'ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaak6haggimwbffytlr72267dwzgv3pbps2t467winmu4erfg5wsdcv';

+---------------------+-------------------------------------------------------------------------------------------------+-----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------
| display_name        | id                                                                                              | lifecycle_state | egress_security_rules                                                                                                                                                       | ingress_security_rules
+---------------------+-------------------------------------------------------------------------------------------------+-----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------
| test-steampipe-rule | ocid1.securitylist.oc1.ap-mumbai-1.aaaaaaaak6haggimwbffytlr72267dwzgv3pbps2t467winmu4nkeeqesz7q | AVAILABLE       | [{"description":null,"destination":"10.0.0.0/16","destinationType":"CIDR_BLOCK","icmpOptions":null,"isStateless":false,"protocol":"1","tcpOptions":null,"udpOptions":null}] | [{"description":null,"icmpOptions":null,"isStateless":false,"protocol":"1","source":"10.0.0.0/16","sourceType":"CIDR_BLOCK","tcpOptions":null,"udpOptions":null}]
+---------------------+-------------------------------------------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------- [...]

2021-04-12 14:07 UTC, khushboo9024 commented on oci/table_oci_core_security_list.go
> +	logger.Debug("oci.getCoreSecurityLists", "Compartment", compartment, "OCI_REGION", region)
```suggestion
	logger.Debug("oci.getCoreSecurityList", "Compartment", compartment, "OCI_REGION", region)
```

2021-04-12 14:09 UTC, khushboo9024 commented on oci/table_oci_core_security_list.go
> +	core.SecurityList
Please use the new function ociRegionName for region column rather than using this custom struct.

2021-04-12 14:14 UTC, khushboo9024 requested changes
Please make the suggested changes and resolve merge conflict also.

2021-04-13 09:45 UTC, khushboo9024 commented on oci-test/tests/oci_core_security_list/variables.tf
> +    oci_identity_group.test_group
why we need `oci_identity_group` ?

2021-04-13 09:46 UTC, khushboo9024 commented on oci-test/tests/oci_core_security_list/variables.tf
> +resource "oci_core_security_list" "named_test_resource" {
`oci_core_security_list` should depends on `oci_core_vcn`.

2021-04-15 06:10 UTC, khushboo9024 commented on oci/table_oci_core_security_list.go
> +
```

2021-04-15 07:00 UTC, khushboo9024 approved these changes
LGTM

2021-04-19 08:24 UTC, rajmohanty17 requested changes
@visiit can we have one security standard example  such as >  Ensure no security lists allow ingress from 0.0.0.0/0 to port 3389 / 22

2021-04-22 10:39 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 19:54 UTC, cbruno10 approved these changes

2021-04-22 19:54 UTC, merged