Add table oci_core_dhcp_options. Closes #50
turbot/steampipe-plugin-oci pull request #75
Opened 2021-04-12 11:57 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Test names: [ 'tests/oci_core_dhcp_option' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_core_dhcp_option []

PRETEST: tests/oci_core_dhcp_option

TEST: tests/oci_core_dhcp_option
Running terraform
oci_core_vcn.named_test_resource: Creating...
oci_core_vcn.named_test_resource: Creation complete after 1s [id=ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaajzq6lawpkjepl3pvbwoqtug4b7vw6zavdcljrj7gf7sq]
oci_core_dhcp_options.named_test_resource: Creating...
oci_core_dhcp_options.named_test_resource: Creation complete after 1s [id=ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaaygdxps5hxbcltfxp6kxsuoyzqwkgalnoybezwb3e5u62mx67beca]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

display_name = "steampipetest6708"
freeform_tags = tomap({
  "Department" = "Finance"
})
region = "ap-mumbai-1"
resource_id = "ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaaygdxps5hxbcltfxp6kxsuoyzqwkgalnoybezwb3e5u62mx67beca"
resource_name = "steampipetest6708"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
vcn_id = "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaajzq6lawpkjepl3pvbwoqtug4b7vw6zavdcljrj7gf7sq"

Running SQL query: test-get-query.sql

[
  {
    "display_name": "steampipetest6708",
    "id": "ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaaygdxps5hxbcltfxp6kxsuoyzqwkgalnoybezwb3e5u62mx67beca",
    "lifecycle_state": "AVAILABLE",
    "vcn_id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaajzq6lawpkjepl3pvbwoqtug4b7vw6zavdcljrj7gf7sq"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "steampipetest6708",
    "id": "ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaaygdxps5hxbcltfxp6kxsuoyzqwkgalnoybezwb3e5u62mx67beca",
    "lifecycle_state": "AVAILABLE",
    "vcn_id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaajzq6lawpkjepl3pvbwoqtug4b7vw6zavdcljrj7gf7sq"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "steampipetest6708"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_dhcp_option

TEARDOWN: tests/oci_core_dhcp_option

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  display_name,
  id,
  time_created,
  lifecycle_state as state,
  region
from
  oci_core_dhcp_option;

+--------------------------------------------+------------------------------------------------------------------------------------------------+---------------------+-----------+-------------+
| display_name                               | id                                                                                             | time_created        | state     | region      |
+--------------------------------------------+------------------------------------------------------------------------------------------------+---------------------+-----------+-------------+
| test2                                      | ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaawf5vqbf6z2jtor7sbt5stidh4yiysat3gia3vq76qkeovodwe7za | 2021-04-12 10:55:46 | AVAILABLE | ap-mumbai-1 |
| Default DHCP Options for vcn-20210308-2057 | ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaazfdbqavqgrfi5fj6xp2rewvts2vvsoaskuebbsr25jev2qzav6sa | 2021-03-08 15:28:02 | AVAILABLE | ap-mumbai-1 |
| Default DHCP Options for testVCN           | ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaaijoaqclopasrdigmukyhnnzepxcauci4bpok6mjffw2uhxu3xeia | 2021-04-08 09:39:08 | AVAILABLE | ap-mumbai-1 |
| test_rajesh                                | ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaa6pi52roka2ywyirpgrdh6qjplxdhgma5tfx7j4qhquhtylzte6sq | 2021-04-12 10:51:39 | AVAILABLE | ap-mumbai-1 |
| Default DHCP Options for vcn-20210315-1512 | ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaa3dtkl7ihwjlrfdhri4t773fl5xcnmqgdyoyrs3a2jtr3oixok5sq | 2021-03-15 09:43:33 | AVAILABLE | ap-mumbai-1 |
+--------------------------------------------+------------------------------------------------------------------------------------------------+---------------------+-----------+-------------+
```

### DHCP options configuration parameters info

```sql
select
  id,
  display_name,
  jsonb_array_elements_text(o -> 'searchDomainNames') as search_domain_names,
  jsonb_array_elements_text(o -> 'customDnsServers') as custom_dns_servers,
  o ->> 'serverType' as server_type,
  o ->> 'type' as type
from
  oci_core_dhcp_option,
  jsonb_array_elements(options) as o;

+------------------------------------------------------------------------------------------------+--------------------------------------------+---------------------------+--------------------+-----------------+------------------+
| id                                                                                             | display_name                               | search_domain_names       | custom_dns_servers | server_type     | type             |
+------------------------------------------------------------------------------------------------+--------------------------------------------+---------------------------+--------------------+-----------------+------------------+
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaa6pi52roka2ywyirpgrdh6qjplxdhgma5tfx7j4qhquhtylzte6sq | test_rajesh                                | vcn03082058.oraclevcn.com | <null>             | <null>          | SearchDomain     |
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaaijoaqclopasrdigmukyhnnzepxcauci4bpok6mjffw2uhxu3xeia | Default DHCP Options for testVCN           | testvcn.oraclevcn.com     | <null>             | <null>          | SearchDomain     |
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaawf5vqbf6z2jtor7sbt5stidh4yiysat3gia3vq76qkeovodwe7za | test2                                      | test.com                  | <null>             | <null>          | SearchDomain     |
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaawf5vqbf6z2jtor7sbt5stidh4yiysat3gia3vq76qkeovodwe7za | test2                                      | <null>                    | 192.168.0.2        | CustomDnsServer | DomainNameServer |
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaawf5vqbf6z2jtor7sbt5stidh4yiysat3gia3vq76qkeovodwe7za | test2                                      | <null>                    | 192.168.0.11       | CustomDnsServer | DomainNameServer |
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaawf5vqbf6z2jtor7sbt5stidh4yiysat3gia3vq76qkeovodwe7za | test2                                      | <null>                    | 192.168.0.19       | CustomDnsServer | DomainNameServer |
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaazfdbqavqgrfi5fj6xp2rewvts2vvsoaskuebbsr25jev2qzav6sa | Default DHCP Options for vcn-20210308-2057 | vcn03082058.oraclevcn.com | <null>             | <null>          | SearchDomain     |
| ocid1.dhcpoptions.oc1.ap-mumbai-1.aaaaaaaa3dtkl7ihwjlrfdhri4t773fl5xcnmqgdyoyrs3a2jtr3oixok5sq | Default DHCP Options for vcn-20210315-1512 | vcn03151513.oraclevcn.com | <null>             | <null>          | SearchDomain     |
+------------------------------------------------------------------------------------------------+--------------------------------------------+---------------------------+--------------------+-----------------+------------------+
```
### Count of DHCP options per VCN

```sql
select
  vcn_id,
  count(*) dhcp_option_count
from
  oci_core_dhcp_option
group by
  vcn_id;

+----------------------------------------------------------------------------------------+-------------------+
| vcn_id                                                                                 | dhcp_option_count |
+----------------------------------------------------------------------------------------+-------------------+
| ocid1.vcn.oc1.ap-mumbai-1.a [...]

2021-04-12 13:59 UTC, khushboo9024 commented on oci/table_oci_core_dhcp_option.go
> +			},
```suggestion
			},
			
```

2021-04-12 14:01 UTC, khushboo9024 requested changes
Table name should be `oci_core_dhcp_options` change accordingly.

2021-04-15 05:44 UTC, khushboo9024 commented on oci-test/tests/oci_core_dhcp_options/variables.tf
> +
```suggestion
```

2021-04-15 05:44 UTC, khushboo9024 commented on oci-test/tests/oci_core_dhcp_options/variables.tf
> +  default     = "OCI"
```suggestion
  default     = "DEFAULT"
```

2021-04-15 05:45 UTC, khushboo9024 commented on oci/table_oci_core_dhcp_options.go
> +		Description: "OCI Core DHCP Option",
```suggestion
		Description: "OCI Core DHCP Options",
```

2021-04-15 05:48 UTC, khushboo9024 reviewed
Please make the small suggested change and resolve merge conflict also.

2021-04-15 11:04 UTC, khushboo9024 approved these changes
LGTM

2021-04-16 09:28 UTC, rajmohanty17 approved these changes
LGTM

2021-04-22 20:14 UTC, merged