Add table oci_cloud_guard_managed_list. Closes #70
turbot/steampipe-plugin-oci pull request #78
Opened 2021-04-13 13:27 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-04-15 06:12 UTC, bigdatasourav commented
```
SETUP: tests/oci_cloud_guard_managed_list []

PRETEST: tests/oci_cloud_guard_managed_list

TEST: tests/oci_cloud_guard_managed_list
Running terraform
oci_cloud_guard_managed_list.named_test_resource: Creating...
oci_cloud_guard_managed_list.named_test_resource: Still creating... [10s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [20s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [30s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [40s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [50s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [1m0s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [1m10s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [1m20s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [1m30s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [1m40s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [1m50s elapsed]
oci_cloud_guard_managed_list.named_test_resource: Still creating... [2m0s elapsed]

Error: 500-InternalError 
Provider version: 4.22.0, released on 2021-04-14.  
Service: Cloud Guard Managed List 
Error Message: Internal error occurred 
OPC request ID: a29de305e86e61403f7f6a68e98fcc31/7C2F5E6465C69EE7A91E1DA6C21B1023/4877569365D97B16C02E5B21EBE4C339 
Suggestion: The service for this resource encountered an error. Please contact support for help with service: Cloud Guard Managed List


  on variables.tf line 30, in resource "oci_cloud_guard_managed_list" "named_test_resource":
  30: resource "oci_cloud_guard_managed_list" "named_test_resource" {


Terraform run failed, skipping SQL queries

✘ FAILED
Terraform run failed, skipping SQL queries

✘ FAILED
Terraform run failed, skipping SQL queries

✘ FAILED
Terraform run failed, skipping SQL queries

✘ FAILED

TEARDOWN: tests/oci_cloud_guard_managed_list

SUMMARY:

✘ tests/oci_cloud_guard_managed_list failed.

0/1 passed.

2021-05-12 20:57 UTC, cbruno10 commented
Closing draft PR, will re-open once blockers are cleared.

2021-05-17 07:13 UTC, bigdatasourav commented
test issue resolved.

2021-05-20 17:08 UTC, khushboo9024 commented on oci/table_ oci_cloud_guard_managed_list.go
> +				Name:        "feed_provider",
Columns are not in alphabetical order.

2021-05-20 17:11 UTC, khushboo9024 requested changes
Minor changes required.

2021-05-21 05:57 UTC, bigdatasourav commented on oci/table_ oci_cloud_guard_managed_list.go
> +				Name:        "feed_provider",
as discussed, updated.

2021-05-21 06:59 UTC, khushboo9024 approved these changes
LGTM

2021-05-21 07:34 UTC, rajmohanty17 approved these changes
LGTM

2021-05-21 18:00 UTC, cbruno10 approved these changes

2021-05-21 18:00 UTC, merged