Add table oci_audit_configuration. Closes #93
turbot/steampipe-plugin-oci pull request #94
Opened 2021-04-19 09:28 UTC by bigdatasourav

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
TEST: tests/oci_audit_configuration
Running terraform
oci_audit_configuration.named_test_resource: Creating...
oci_audit_configuration.named_test_resource: Creation complete after 6s [id=ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

retention_period_days = 365
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"

Running SQL query: test-list-query.sql
	
[
  {
    "retention_period_days": 365,
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
  }
]
✔ PASSED

POSTTEST: tests/oci_audit_configuration

TEARDOWN: tests/oci_audit_configuration

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-05-11 06:29 UTC, khushboo9024 commented on oci-test/tests/oci_audit_configuration/test-list-query.sql
> +select retention_period_days,tenant_id
```suggestion
select retention_period_days, tenant_id
```

2021-05-11 06:29 UTC, khushboo9024 commented on oci-test/tests/oci_audit_configuration/test-not-found-query.sql
> +select retention_period_days,tenant_id
```suggestion
select retention_period_days, tenant_id
```

2021-05-11 06:34 UTC, khushboo9024 commented on oci/plugin.go
> +			"oci_audit_configuration":            tableAuditConfiguration(ctx),
Sort the list.

2021-05-11 06:40 UTC, khushboo9024 commented on oci/service.go
> +// coreVirtualNetworkService returns the service client for OCI Audit Service
```suggestion
// auditService returns the service client for OCI Audit Service
```

2021-05-11 06:48 UTC, khushboo9024 requested changes
Please make suggested changes and resolve merge conflict.

2021-05-11 08:28 UTC, khushboo9024 commented on oci/service.go
> -		CloudGuardClient: client,
why we are removing `CloudGuardClient` ?

2021-05-11 08:36 UTC, khushboo9024 approved these changes
LGTM

2021-05-12 13:15 UTC, bigdatasourav commented
can fetch retention period from https://github.com/turbot/steampipe-plugin-oci/issues/105

2021-05-12 13:15 UTC, closed without merging