Add table oci_core_network_security_group. Closes #92
turbot/steampipe-plugin-oci pull request #95
Opened 2021-04-19 09:30 UTC by khushboo9024

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Test names: [ 'tests/oci_core_network_security_group' ]
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_core_network_security_group []

PRETEST: tests/oci_core_network_security_group

TEST: tests/oci_core_network_security_group
Running terraform
oci_core_vcn.test_vcn: Creating...
oci_core_vcn.test_vcn: Creation complete after 1s [id=ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaazk7fc4sothrufxxuslavrujb4g7u5mx7gihgznxe5z7a]
oci_core_network_security_group.named_test_resource: Creating...
oci_core_network_security_group.named_test_resource: Creation complete after 0s [id=ocid1.networksecuritygroup.oc1.ap-mumbai-1.aaaaaaaavtozctw6kwxa33ltfqczeyzxdnxkvdnyy5ytemqvv6fwf7g6ymna]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

display_name = steampipetest7276
freeform_tags = {
  "Name" = "steampipetest7276"
}
resource_id = ocid1.networksecuritygroup.oc1.ap-mumbai-1.aaaaaaaavtozctw6kwxa33ltfqczeyzxdnxkvdnyy5ytemqvv6fwf7g6ymna
resource_name = steampipetest7276
tenancy_ocid = ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq
vcn_id = ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaazk7fc4sothrufxxuslavrujb4g7u5mx7gihgznxe5z7a

Running SQL query: test-get-query.sql

[
  {
    "display_name": "steampipetest7276",
    "freeform_tags": {
      "Name": "steampipetest7276"
    },
    "id": "ocid1.networksecuritygroup.oc1.ap-mumbai-1.aaaaaaaavtozctw6kwxa33ltfqczeyzxdnxkvdnyy5ytemqvv6fwf7g6ymna",
    "lifecycle_state": "AVAILABLE",
    "vcn_id": "ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaazk7fc4sothrufxxuslavrujb4g7u5mx7gihgznxe5z7a"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "steampipetest7276",
    "id": "ocid1.networksecuritygroup.oc1.ap-mumbai-1.aaaaaaaavtozctw6kwxa33ltfqczeyzxdnxkvdnyy5ytemqvv6fwf7g6ymna",
    "lifecycle_state": "AVAILABLE"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "steampipetest7276"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_network_security_group

TEARDOWN: tests/oci_core_network_security_group

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
## Examples

### Basic info

```sql
select
  display_name,
  id,
  vcn_id,
  lifecycle_state as state,
  time_created
from
  oci_core_network_security_group;
+--------------+---------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-----------+---------------------+
| display_name | id                                                                                                      | vcn_id                                                                                 | state     | time_created        |
+--------------+---------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-----------+---------------------+
| test45       | ocid1.networksecuritygroup.oc1.ap-mumbai-1.aaaaaaaabaxzcu6na2dt4metytun2bdtvac3sfccjllknlognm4lfwqzzyra | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa24wsljja2vtzqod3j5rceq4svwyrjs2i56z254vvw55a | AVAILABLE | 2021-04-19 08:42:50 |
| test-new     | ocid1.networksecuritygroup.oc1.ap-mumbai-1.aaaaaaaaihpqyj6tljb4g7ff6ylcioke6pqwm76esvda3bp6m4vcaics7e3q | ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa24wsljja2vtzqod3j5rceq4svwyrjs2i56z254vvw55a | AVAILABLE | 2021-04-19 08:44:21 |
| tes89        | ocid1.networksecuritygroup.oc1.iad.aaaaaaaawmkxr6tislfwqldxtsbva27qmrv4jyuthb2gh46zc5eeu45jd6va         | ocid1.vcn.oc1.iad.amaaaaaa6igdexaapxc5rzgmxuqojzyia4vsnf4r6ic4n5avu66uwkb3rhba         | AVAILABLE | 2021-04-19 08:45:04 |
| test-comp    | ocid1.networksecuritygroup.oc1.iad.aaaaaaaanlkmptkrustzspuxvyses6psdbefcejs2df5a2akqbnc5wac7bjq         | ocid1.vcn.oc1.iad.amaaaaaa6igdexaa2heejwnc5wui2rpu74kf23ij55pka75sorxstu7twrsa         | AVAILABLE | 2021-04-19 08:45:44 |
+--------------+---------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-----------+---------------------+
```

### List NSG which are not in availabe state

```sql
select
  display_name,
  id,
  lifecycle_state as state
from
  oci_core_network_security_group
where
 lifecycle_state <> 'AVAILABLE';
+--------------+----+-------+
| display_name | id | state |
+--------------+----+-------+
+--------------+----+-------+
```

### Count of NSG per vcn

```sql
select
  vcn_id,
  count(id) as no_of_nsg
from
  oci_core_network_security_group
group by
  vcn_id;
+----------------------------------------------------------------------------------------+-----------+
| vcn_id                                                                                 | no_of_nsg |
+----------------------------------------------------------------------------------------+-----------+
| ocid1.vcn.oc1.ap-mumbai-1.amaaaaaa6igdexaa24wsljja2vtzqod3j5rceq4svwyrjs2i56z254vvw55a | 2         |
| ocid1.vcn.oc1.iad.amaaaaaa6igdexaa2heejwnc5wui2rpu74kf23ij55pka75sorxstu7twrsa         | 1         |
| ocid1.vcn.oc1.iad.amaaaaaa6igdexaapxc5rzgmxuqojzyia4vsnf4r6ic4n5avu66uwkb3rhba         | 1         |
+----------------------------------------------------------------------------------------+-----------+
```
```
</details>

2021-04-26 05:42 UTC, khushboo9024 commented on oci/table_oci_core_network_security_group.go
> +				Name:        "display_name",
@LalitTurbot  we have ingress/egress rules defined in table `oci_core_security_list`.

2021-04-26 05:44 UTC, khushboo9024 commented on docs/tables/oci_core_network_security_group.md
> +```
@LalitTurbot  we have these examples in table `oci_core_security_list`.

2021-04-27 07:39 UTC, rajmohanty17 requested changes
Can we achieve followings or its part of some other table
Ensure Security groups do not have an excessive number of rules defined.
No security groups, that open range of ports to allow incoming traffic.

2021-05-18 09:50 UTC, rajmohanty17 approved these changes
LGTM

2021-05-19 21:09 UTC, cbruno10 approved these changes

2021-05-19 21:10 UTC, merged