Add table oci_core_volume_backup_policy. CLoses #96
turbot/steampipe-plugin-oci pull request #99
Opened 2021-04-19 14:02 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
Test names: [ 'tests/oci_core_volume_backup_policy' ]
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging

SETUP: tests/oci_core_volume_backup_policy []

PRETEST: tests/oci_core_volume_backup_policy

TEST: tests/oci_core_volume_backup_policy
Running terraform
oci_core_volume_backup_policy.named_test_resource: Creating...
oci_core_volume_backup_policy.named_test_resource: Creation complete after 2s [id=ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaa5rfkicmz6by7bxwsvhbd5cglya7acbiss3lfay4tf3zii5lmqu6a]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

region = "ap-mumbai-1"
resource_id = "ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaa5rfkicmz6by7bxwsvhbd5cglya7acbiss3lfay4tf3zii5lmqu6a"
resource_name = "steampipetest1616"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"

Running SQL query: test-get-query.sql

[
  {
    "display_name": "steampipetest1616",
    "freeform_tags": {
      "Name": "steampipetest1616"
    },
    "id": "ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaa5rfkicmz6by7bxwsvhbd5cglya7acbiss3lfay4tf3zii5lmqu6a",
    "region": "ap-mumbai-1"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "display_name": "steampipetest1616",
    "freeform_tags": {
      "Name": "steampipetest1616"
    },
    "id": "ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaa5rfkicmz6by7bxwsvhbd5cglya7acbiss3lfay4tf3zii5lmqu6a",
    "region": "ap-mumbai-1"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq",
    "title": "steampipetest1616"
  }
]
✔ PASSED

POSTTEST: tests/oci_core_volume_backup_policy

TEARDOWN: tests/oci_core_volume_backup_policy

SUMMARY:

1/1 passed.

# Example query results
<details>
  <summary>Results</summary>
  
```
### Basic info

```sql
select
  id,
  display_name,
  time_created,
  region,
  tags
from
  oci_core_volume_backup_policy;

+-------------------------------------------------------------------------------------------------------+--------------+---------------------+-------------+------------------------------------------------------------------------------+
| id                                                                                                    | display_name | time_created        | region      | tags                                                                         |
+-------------------------------------------------------------------------------------------------------+--------------+---------------------+-------------+------------------------------------------------------------------------------+
| ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaahtfydyy3vbbaexrhggur6p2l2qhdz4halvsno7z7n6kjjtb7ui6a | test         | 2021-04-19 12:28:33 | ap-mumbai-1 | {"CreatedBy":"rajesh_bal","CreatedOn":"2021-04-19T12:28:33.182Z","df":"wfw"} |
| ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaah5yqtcvtvufi567gdjcsgrwg4nskuflfn6j2rtznnv2pgz2q2pta | test2        | 2021-04-19 13:43:37 | ap-mumbai-1 | {"CreatedBy":"rajesh_bal","CreatedOn":"2021-04-19T13:43:37.523Z"}            |
+-------------------------------------------------------------------------------------------------------+--------------+---------------------+-------------+------------------------------------------------------------------------------+
```

### List the destination regions of volume back up policy

```sql
select
  id,
  display_name,
  destination_region
from
  oci_core_volume_backup_policy;

+-------------------------------------------------------------------------------------------------------+--------------+--------------------+
| id                                                                                                    | display_name | destination_region |
+-------------------------------------------------------------------------------------------------------+--------------+--------------------+
| ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaah5yqtcvtvufi567gdjcsgrwg4nskuflfn6j2rtznnv2pgz2q2pta | test2        | ap-hyderabad-1     |
| ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaahtfydyy3vbbaexrhggur6p2l2qhdz4halvsno7z7n6kjjtb7ui6a | test         | ap-hyderabad-1     |
+-------------------------------------------------------------------------------------------------------+--------------+--------------------+
```

### List schedule info of volume backup policy

```sql
select
  id,
  display_name,
  s ->> 'backupType' as backup_type,
  s ->> 'dayOfMonth' as day_of_month,
  s ->> 'dayOfWeek' as day_of_week,
  s ->> 'hourOfDay' as hour_of_day,
  s ->> 'month' as month,
  s ->> 'offsetSeconds' as offset_econds,
  s ->> 'offsetType' as offset_type,
  s ->> 'period' as offset_econds,
  s ->> 'retentionSeconds' as retention_seconds,
  s ->> 'timeZone' as time_zone
from
  oci_core_volume_backup_policy,
  jsonb_array_elements(schedules) as s;

+-------------------------------------------------------------------------------------------------------+--------------+-------------+--------------+-------------+-------------+---------+---------------+-------------+---------------+-------------------+-----------+
| id                                                                                                    | display_name | backup_type | day_of_month | day_of_week | hour_of_day | month   | offset_econds | offset_type | offset_econds | retention_seconds | time_zone |
+-------------------------------------------------------------------------------------------------------+--------------+-------------+--------------+-------------+-------------+---------+---------------+-------------+---------------+-------------------+-----------+
| ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaahtfydyy3vbbaexrhggur6p2l2qhdz4halvsno7z7n6kjjtb7ui6a | test         | INCREMENTAL | 1            | MONDAY      | 0           | JANUARY | 0             | STRUCTURED  | ONE_WEEK      | 604800            | UTC       |
| ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaahtfydyy3vbbaexrhggur6p2l2qhdz4halvsno7z7n6kjjtb7ui6a | test         | FULL        | 1            | TUESDAY     | 0           | JANUARY | 0             | STRUCTURED  | ONE_YEAR      | 31536000          | UTC       |
+-------------------------------------------------------------------------------------------------------+--------------+-------------+--------------+-------------+-------------+---------+---------------+-------------+---------------+-------------------+-----------+
```

```sql
select
  id,
  display_name,
  s ->> 'backupType' as backup_type,
  s ->> 'backupType' as backup_type
from
  oci_core_volume_backup_policy,
  jsonb_array_elements(schedules) as s
where
  s ->> 'backupType' = 'FULL';

+-------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| id                                                                                                    | display_name | backup_type | backup_type |
+-------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
| ocid1.volumebackuppolicy.oc1.ap-mumbai-1.aaaaaaaahtfydyy3vbbaexrhggur6p2l2qhdz4halvsno7z7n6kjjtb7ui6a | test         | FULL        | FULL        |
+-------------------------------------------------------------------------------------------------------+--------------+-------------+-------------+
```
</details>

2021-04-19 14:17 UTC, khushboo9024 commented on oci/table_oci_core_volume_backup_policy.go
> +	// handle empty volume id in get call
```suggestion
	// handle empty volume backup policy id in get call
```

2021-04-19 14:33 UTC, khushboo9024 commented on oci/table_oci_core_volume_backup_policy.go
> +				Description: "ColumnDescriptionCompartment",
```suggestion
				Description: ColumnDescriptionCompartment,
```

2021-04-19 14:37 UTC, khushboo9024 requested changes
Minor changes required.

2021-04-26 07:55 UTC, khushboo9024 commented on docs/tables/oci_core_volume_backup_policy.md
> +### List the destination regions of volume back up policy
```suggestion
### List the destination regions of volume backup policy
```

2021-04-26 07:56 UTC, khushboo9024 commented on oci/table_oci_core_volume_backup_policy.go
> +			KeyColumns: plugin.AnyColumn([]string{"id"}),
```suggestion
			KeyColumns: plugin.SingleColumn("id"),
```

2021-04-26 08:02 UTC, khushboo9024 requested changes
Please make suggested changes and resolve merge conflict.

2021-04-27 10:02 UTC, khushboo9024 approved these changes
LGTM

2021-05-12 08:30 UTC, rajmohanty17 approved these changes
LGTM

2021-05-12 21:07 UTC, cbruno10 approved these changes

2021-05-12 21:07 UTC, merged